static const String godot2Title[3] = {"Waiting", "for Godot", "Act Two"};
static const int godot2Length = 49581;
static const char godot2[] PROGMEM = "Waiting for Godot ACT II\n"
"Next day. Same time. Same place.\n"
"Estragon's boots front center, heels together, toes splayed. \n"
"Lucky's hat at same place.\n"
"The tree has four or five leaves.\n"
"Enter Vladimir agitatedly. He halts and looks long at the tree, then suddenly begins to move feverishly about the stage. He halts before the boots, picks one up, examines it, sniffs it, manifests disgust, puts it back carefully. Comes and goes. Halts extreme right and gazes into distance off, shading his eyes with his hand. Comes and goes. Halts extreme left, as before. Comes and goes. Halts suddenly and begins to sing loudly.\n"
"VLADIMIR:\n"
"A dog came in–\n"
"Having begun too high he stops, clears his throat, resumes:\n"
"A dog came in the kitchen And stole a crust of bread. Then cook up with a ladle And beat him till he was dead.\n"
"Then all the dogs came running And dug the dog a tomb–\n"
"He stops, broods, resumes:\n"
"Then all the dogs came running And dug the dog a tomb\n"
"And wrote upon the tombstone For the eyes of dogs to come:\n"
"A dog came in the kitchen And stole a crust of bread. Then cook up with a ladle And beat him till he was dead.\n"
"Then all the dogs came running And dug the dog a tomb–\n"
"He stops, broods, resumes:\n"
"Then all the dogs came running And dug the dog a tomb–\n"
"He stops, broods. Softly.\n"
"And dug the dog a tomb ...\n"
"He remains a moment silent and motionless, then begins to move feverishly about the stage. He halts before the tree, comes and goes, before the boots, comes and goes, halts extreme right, gazes into distance, extreme left, gazes into distance. Enter Estragon right, barefoot, head bowed. He slowly crosses the stage. Vladimir turns and sees him.\n"
"VLADIMIR:\n"
"You again! (Estragon halts but does not raise his head. Vladimir goes towards him.) Come here till I embrace you.\n"
"ESTRAGON:\n"
"Don't touch me!\n"
"Vladimir holds back, pained. VLADIMIR:\n"
"Do you want me to go away? (Pause.) Gogo! (Pause. Vladimir observes him attentively.) Did they beat you? (Pause.) Gogo! (Estragon remains silent, head bowed.) Where did you spend the night?\n"
"ESTRAGON:\n"
"Don't touch me! Don't question me! Don't speak to me! Stay with me!\n"
"VLADIMIR:\n"
"Did I ever leave you? ESTRAGON:\n"
"You let me go. VLADIMIR:\n"
"Look at me. (Estragon does not raise his head. Violently.) Will you look at me! Estragon raises his head. They look long at each other, then suddenly embrace, clapping each other on the back. End of the embrace. Estragon, no longer supported, almost falls.\n"
"ESTRAGON: What a day!\n"
"VLADIMIR:\n"
"Who beat you? Tell me.\n"
"ESTRAGON:\n"
"Another day done with.\n"
"VLADIMIR: Not yet.\n"
"ESTRAGON:\n"
"For me it's over and done with, no matter what happens. (Silence.) I heard you singing.\n"
"VLADIMIR:\n"
"That's right, I remember.\n"
"ESTRAGON:\n"
"That finished me. I said to myself, He's all alone, he thinks I'm gone for ever, and he sings.\n"
"VLADIMIR:\n"
"One is not master of one's moods. All day I've felt in great form. (Pause.) I didn't get up in the night, not once!\n"
"ESTRAGON:\n"
"(sadly). You see, you piss better when I'm not there.\n"
"VLADIMIR:\n"
"I missed you ... and at the same time I was happy. Isn't that a strange thing?\n"
"ESTRAGON: (shocked). Happy?\n"
"VLADIMIR:\n"
"Perhaps it's not quite the right word.\n"
"ESTRAGON: And now?\n"
"VLADIMIR:\n"
"Now? ... (Joyous.) There you are again ... (Indifferent.) There we are again... (Gloomy.) There I am again.\n"
"ESTRAGON:\n"
"You see, you feel worse when I'm with you. I feel better alone too.\n"
"VLADIMIR:\n"
"(vexed). Then why do you always come crawling back?\n"
"ESTRAGON:\n"
"I don't know.\n"
"VLADIMIR:\n"
"No, but I do. It's because you don't know how to defend yourself. I wouldn't have let them beat you.\n"
"ESTRAGON:\n"
"You couldn't have stopped them.\n"
"VLADIMIR: Why not?\n"
"ESTRAGON:\n"
"There was ten of them.\n"
"VLADIMIR:\n"
"No, I mean before they beat you. I would have stopped you from doing whatever it was you were doing.\n"
"ESTRAGON:\n"
"I wasn't doing anything.\n"
"VLADIMIR:\n"
"Then why did they beat you?\n"
"ESTRAGON:\n"
"I don't know.\n"
"VLADIMIR:\n"
"Ah no, Gogo, the truth is there are things that escape you that don't escape me, you must feel it yourself.\n"
"ESTRAGON:\n"
"I tell you I wasn't doing anything.\n"
"VLADIMIR:\n"
"Perhaps you weren't. But it's the way of doing it that counts, the way of doing it, if you want to go on living.\n"
"ESTRAGON:\n"
"I wasn't doing anything.\n"
"VLADIMIR:\n"
"You must be happy too, deep down, if you only knew it.\n"
"ESTRAGON:\n"
"Happy about what?\n"
"VLADIMIR:\n"
"To be back with me again.\n"
"ESTRAGON:\n"
"Would you say so?\n"
"VLADIMIR:\n"
"Say you are, even if it's not true.\n"
"ESTRAGON:\n"
"What am I to say?\n"
"VLADIMIR:\n"
"Say, I am happy.\n"
"ESTRAGON:\n"
"I am happy.\n"
"VLADIMIR: So am I. ESTRAGON: So am I.\n"
"VLADIMIR:\n"
"We are happy.\n"
"ESTRAGON:\n"
"We are happy. (Silence.) What do we do now, now that we are happy?\n"
"VLADIMIR:\n"
"Wait for Godot. (Estragon groans. Silence.) Things have changed here since yesterday.\n"
"ESTRAGON:\n"
"And if he doesn't come?\n"
"VLADIMIR:\n"
"(after a moment of bewilderment). We'll see when the time comes. (Pause.) I was saying that things have changed here since yesterday.\n"
"ESTRAGON: Everything oozes.\n"
"VLADIMIR:\n"
"Look at the tree.\n"
"ESTRAGON:\n"
"It's never the same pus from one second to the next.\n"
"VLADIMIR:\n"
"The tree, look at the tree. Estragon looks at the tree.\n"
"ESTRAGON:\n"
"Was it not there yesterday?\n"
"VLADIMIR:\n"
"Yes of course it was there. Do you not remember? We nearly hanged ourselves from it. But you wouldn't. Do you not remember?\n"
"ESTRAGON:\n"
"You dreamt it.\n"
"VLADIMIR:\n"
"Is it possible you've forgotten already?\n"
"ESTRAGON:\n"
"That's the way I am. Either I forget immediately or I never forget.\n"
"VLADIMIR:\n"
"And Pozzo and Lucky, have you forgotten them too?\n"
"ESTRAGON:\n"
"Pozzo and Lucky?\n"
"VLADIMIR:\n"
"He's forgotten everything!\n"
"ESTRAGON:\n"
"I remember a lunatic who kicked the shins off me. Then he played the fool.\n"
"VLADIMIR:\n"
"That was Lucky.\n"
"ESTRAGON:\n"
"I remember that. But when was it?\n"
"VLADIMIR:\n"
"And his keeper, do you not remember him?\n"
"ESTRAGON:\n"
"He gave me a bone.\n"
"VLADIMIR:\n"
"That was Pozzo.\n"
"ESTRAGON:\n"
"And all that was yesterday, you say?\n"
"VLADIMIR:\n"
"Yes of course it was yesterday.\n"
"ESTRAGON:\n"
"And here where we are now?\n"
"VLADIMIR:\n"
"Where else do you think? Do you not recognize the place?\n"
"ESTRAGON:\n"
"(suddenly furious). Recognize! What is there to recognize? All my lousy life I've crawled about in the mud! And you talk to me about scenery! (Looking wildly about him.) Look at this muckheap! I've never stirred from it!\n"
"VLADIMIR:\n"
"Calm yourself, calm yourself.\n"
"ESTRAGON:\n"
"You and your landscapes! Tell me about the worms!\n"
"VLADIMIR:\n"
"All the same, you can't tell me that this (gesture) bears any resemblance to ... (he hesitates) ... to the Macon country for example. You can't deny there's a big difference.\n"
"ESTRAGON:\n"
"The Macon country! Who's talking to you about the Macon country?\n"
"VLADIMIR:\n"
"But you were there yourself, in the Macon country.\n"
"ESTRAGON:\n"
"No I was never in the Macon country! I've puked my puke of a life away here, I tell you! Here! In the Cackon country!\n"
"VLADIMIR:\n"
"But we were there together, I could swear to it! Picking grapes for a man called ... (he snaps his fingers) ... can't think of the name of the man, at a place called ... (snaps his fingers) ... can't think of the name of the place, do you not remember?\n"
"ESTRAGON:\n"
"(a little calmer). It's possible. I didn't notice anything.\n"
"VLADIMIR:\n"
"But down there everything is red!\n"
"ESTRAGON:\n"
"(exasperated). I didn't notice anything, I tell you! Silence. Vladimir sighs deeply.\n"
"VLADIMIR:\n"
"You're a hard man to get on with, Gogo.\n"
"ESTRAGON:\n"
"It'd be better if we parted.\n"
"VLADIMIR:\n"
"You always say that and you always come crawling back.\n"
"ESTRAGON:\n"
"The best thing would be to kill me, like the other.\n"
"VLADIMIR:\n"
"What other? (Pause.) What other?\n"
"ESTRAGON:\n"
"Like billions of others.\n"
"VLADIMIR:\n"
"(sententious). To every man his little cross. (He sighs.) Till he dies. (Afterthought.) And is forgotten.\n"
"ESTRAGON:\n"
"In the meantime let us try and converse calmly, since we are incapable of keeping silent.\n"
"VLADIMIR:\n"
"You're right, we're inexhaustible.\n"
"ESTRAGON:\n"
"It's so we won't think.\n"
"VLADIMIR:\n"
"We have that excuse.\n"
"ESTRAGON:\n"
"It's so we won't hear.\n"
"VLADIMIR:\n"
"We have our reasons.\n"
"ESTRAGON:\n"
"All the dead voices.\n"
"VLADIMIR:\n"
"They make a noise like wings.\n"
"ESTRAGON: Like leaves.\n"
"VLADIMIR: Like sand.\n"
"ESTRAGON: Like leaves.\n"
"Silence. VLADIMIR:\n"
"They all speak at once. ESTRAGON:\n"
"Each one to itself.\n"
"Silence. VLADIMIR:\n"
"Rather they whisper. ESTRAGON:\n"
"They rustle. VLADIMIR:\n"
"They murmur. ESTRAGON:\n"
"They rustle.\n"
"Silence. VLADIMIR:\n"
"What do they say? ESTRAGON:\n"
"They talk about their lives. VLADIMIR:\n"
"To have lived is not enough for them. ESTRAGON:\n"
"They have to talk about it. VLADIMIR:\n"
"To be dead is not enough for them. ESTRAGON:\n"
"It is not sufficient.\n"
"Silence. VLADIMIR:\n"
"They make a noise like feathers. ESTRAGON:\n"
"Like leaves. VLADIMIR:\n"
"Likes ashes. ESTRAGON:\n"
"Like leaves.\n"
"Long silence. VLADIMIR:\n"
"Say something! ESTRAGON:\n"
"I'm trying.\n"
"Long silence. VLADIMIR:\n"
"(in anguish). Say anything at all! ESTRAGON:\n"
"What do we do now? VLADIMIR:\n"
"Wait for Godot. ESTRAGON:\n"
"Ah!\n"
"Silence. VLADIMIR:\n"
"This is awful! ESTRAGON:\n"
"Sing something. VLADIMIR:\n"
"No no! (He reflects.) We could start all over again perhaps. ESTRAGON:\n"
"That should be easy. VLADIMIR:\n"
"It's the start that's difficult. ESTRAGON:\n"
"You can start from anything. VLADIMIR:\n"
"Yes, but you have to decide. ESTRAGON:\n"
"True.\n"
"Silence. VLADIMIR:\n"
"Help me! ESTRAGON:\n"
"I'm trying.\n"
"Silence. VLADIMIR:\n"
"When you seek you hear. ESTRAGON:\n"
"You do. VLADIMIR:\n"
"That prevents you from finding. ESTRAGON:\n"
"It does. VLADIMIR:\n"
"That prevents you from thinking. ESTRAGON:\n"
"You think all the same. VLADIMIR:\n"
"No no, it's impossible. ESTRAGON:\n"
"That's the idea, let's contradict each another. VLADIMIR:\n"
"Impossible. ESTRAGON:\n"
"You think so? VLADIMIR:\n"
"We're in no danger of ever thinking any more. ESTRAGON:\n"
"Then what are we complaining about? VLADIMIR:\n"
"Thinking is not the worst. ESTRAGON:\n"
"Perhaps not. But at least there's that. VLADIMIR:\n"
"That what? ESTRAGON:\n"
"That's the idea, let's ask each other questions. VLADIMIR:\n"
"What do you mean, at least there's that? ESTRAGON:\n"
"That much less misery. VLADIMIR:\n"
"True. ESTRAGON:\n"
"Well? If we gave thanks for our mercies? VLADIMIR:\n"
"What is terrible is to have thought. ESTRAGON:\n"
"But did that ever happen to us? VLADIMIR:\n"
"Where are all these corpses from? ESTRAGON:\n"
"These skeletons. VLADIMIR:\n"
"Tell me that. ESTRAGON:\n"
"True. VLADIMIR:\n"
"We must have thought a little. ESTRAGON:\n"
"At the very beginning. VLADIMIR:\n"
"A charnel­house! A charnel­house! ESTRAGON:\n"
"You don't have to look. VLADIMIR:\n"
"You can't help looking. ESTRAGON:\n"
"True. VLADIMIR:\n"
"Try as one may. ESTRAGON:\n"
"I beg your pardon? VLADIMIR:\n"
"Try as one may. ESTRAGON:\n"
"We should turn resolutely towards Nature. VLADIMIR:\n"
"We've tried that. ESTRAGON:\n"
"True. VLADIMIR:\n"
"Oh it's not the worst, I know. ESTRAGON:\n"
"What? VLADIMIR:\n"
"To have thought. ESTRAGON:\n"
"Obviously. VLADIMIR:\n"
"But we could have done without it. ESTRAGON:\n"
"Que voulez­vous? VLADIMIR:\n"
"I beg your pardon? ESTRAGON:\n"
"Que voulez­vouz. VLADIMIR:\n"
"Ah! que voulez­vous. Exactly.\n"
"Silence. ESTRAGON:\n"
"That wasn't such a bad little canter. VLADIMIR:\n"
"Yes, but now we'll have to find something else. ESTRAGON:\n"
"Let me see.\n"
"He takes off his hat, concentrates. VLADIMIR:\n"
"Let me see. (He takes off his hat, concentrates. Long silence.) Ah!\n"
"They put on their hats, relax. ESTRAGON:\n"
"Well? VLADIMIR:\n"
"What was I saying, we could go on from there. ESTRAGON:\n"
"What were you saying when? VLADIMIR:\n"
"At the very beginning. ESTRAGON:\n"
"The very beginning of WHAT? VLADIMIR:\n"
"This evening ... I was saying ... I was saying ... ESTRAGON:\n"
"I'm not a historian. VLADIMIR:\n"
"Wait ... we embraced ... we were happy ... happy ... what do we do now that we're happy ... go on waiting ... waiting ... let me think ... it's coming ... go on waiting ... now that we're happy ... let me see ... ah! The tree!\n"
"ESTRAGON: The tree?\n"
"VLADIMIR:\n"
"Do you not remember?\n"
"ESTRAGON: I'm tired.\n"
"VLADIMIR: Look at it.\n"
"They look at the tree. ESTRAGON:\n"
"I see nothing. VLADIMIR:\n"
"But yesterday evening it was all black and bare. And now it's covered with leaves. ESTRAGON:\n"
"Leaves? VLADIMIR:\n"
"In a single night. ESTRAGON:\n"
"It must be the Spring. VLADIMIR:\n"
"But in a single night! ESTRAGON:\n"
"I tell you we weren't here yesterday. Another of your nightmares. VLADIMIR:\n"
"And where were we yesterday evening according to you? ESTRAGON:\n"
"How would I know? In another compartment. There's no lack of void. VLADIMIR:\n"
"(sure of himself). Good. We weren't here yesterday evening. Now what did we do\n"
"yesterday evening? ESTRAGON:\n"
"Do? VLADIMIR:\n"
"Try and remember. ESTRAGON:\n"
"Do ... I suppose we blathered. VLADIMIR:\n"
"(controlling himself). About what? ESTRAGON:\n"
"Oh ... this and that I suppose, nothing in particular. (With assurance.) Yes, now I remember, yesterday evening we spent blathering about nothing in particular. That's been going on now for half a century.\n"
"VLADIMIR:\n"
"You don't remember any fact, any circumstance?\n"
"ESTRAGON:\n"
"(weary). Don't torment me, Didi.\n"
"VLADIMIR:\n"
"The sun. The moon. Do you not remember?\n"
"ESTRAGON:\n"
"They must have been there, as usual.\n"
"VLADIMIR:\n"
"You didn't notice anything out of the ordinary?\n"
"ESTRAGON: Alas!\n"
"VLADIMIR:\n"
"And Pozzo? And Lucky?\n"
"ESTRAGON: Pozzo?\n"
"VLADIMIR: The bones.\n"
"ESTRAGON:\n"
"They were like fishbones.\n"
"VLADIMIR:\n"
"It was Pozzo gave them to you.\n"
"ESTRAGON:\n"
"I don't know.\n"
"VLADIMIR:\n"
"And the kick.\n"
"ESTRAGON:\n"
"That's right, someone gave me a kick.\n"
"VLADIMIR:\n"
"It was Lucky gave it to you.\n"
"ESTRAGON:\n"
"And all that was yesterday?\n"
"VLADIMIR:\n"
"Show me your leg.\n"
"ESTRAGON: Which? VLADIMIR:\n"
"Both. Pull up your trousers. (Estragon gives a leg to Vladimir, staggers. Vladimir takes\n"
"the leg. They stagger.) Pull up your trousers. ESTRAGON:\n"
"I can't.\n"
"Vladimir pulls up the trousers, looks at the leg, lets it go. Estragon almost falls. VLADIMIR:\n"
"The other. (Estragon gives the same leg.) The other, pig! (Estragon gives the other leg.\n"
"Triumphantly.) There's the wound! Beginning to fester! ESTRAGON:\n"
"And what about it? VLADIMIR:\n"
"(letting go the leg). Where are your boots? ESTRAGON:\n"
"I must have thrown them away. VLADIMIR:\n"
"When? ESTRAGON:\n"
"I don't know. VLADIMIR:\n"
"Why? ESTRAGON:\n"
"(exasperated). I don't know why I don't know! VLADIMIR:\n"
"No, I mean why did you throw them away? ESTRAGON:\n"
"(exasperated). Because they were hurting me! VLADIMIR:\n"
"(triumphantly, pointing to the boots). There they are! (Estragon looks at the boots.) At the very spot where you left them yesterday!\n"
"Estragon goes towards the boots, inspects them closely.\n"
"ESTRAGON:\n"
"They're not mine.\n"
"VLADIMIR:\n"
"(stupefied). Not yours!\n"
"ESTRAGON:\n"
"Mine were black. These are brown.\n"
"VLADIMIR:\n"
"You're sure yours were black?\n"
"ESTRAGON:\n"
"Well they were a kind of gray.\n"
"VLADIMIR:\n"
"And these are brown. Show me.\n"
"ESTRAGON:\n"
"(picking up a boot). Well they're a kind of green.\n"
"VLADIMIR:\n"
"Show me. (Estragon hands him the boot. Vladimir inspects it, throws it down angrily.) Well of all the—\n"
"ESTRAGON:\n"
"You see, all that's a lot of bloody—\n"
"VLADIMIR:\n"
"Ah! I see what it is. Yes, I see what's happened.\n"
"ESTRAGON:\n"
"All that's a lot of bloody—\n"
"VLADIMIR:\n"
"It's elementary. Someone came and took yours and left you his.\n"
"ESTRAGON: Why?\n"
"VLADIMIR:\n"
"His were too tight for him, so he took yours.\n"
"ESTRAGON:\n"
"But mine were too tight.\n"
"VLADIMIR:\n"
"For you. Not for him.\n"
"ESTRAGON:\n"
"(having tried in vain to work it out). I'm tired! (Pause.) Let's go.\n"
"VLADIMIR: We can't.\n"
"ESTRAGON: Why not?\n"
"VLADIMIR:\n"
"We're waiting for Godot.\n"
"ESTRAGON:\n"
"Ah! (Pause. Despairing.) What'll we do, what'll we do!\n"
"VLADIMIR:\n"
"There's nothing we can do.\n"
"ESTRAGON:\n"
"But I can't go on like this!\n"
"VLADIMIR:\n"
"Would you like a radish?\n"
"ESTRAGON:\n"
"Is that all there is?\n"
"VLADIMIR:\n"
"There are radishes and turnips.\n"
"ESTRAGON:\n"
"Are there no carrots?\n"
"VLADIMIR:\n"
"No. Anyway you overdo it with your carrots.\n"
"ESTRAGON:\n"
"Then give me a radish. (Vladimir fumbles in his pockets, finds nothing but turnips, finally brings out a radish and hands it to Estragon who examines it, sniffs it.) It's black!\n"
"VLADIMIR:\n"
"It's a radish.\n"
"ESTRAGON:\n"
"I only like the pink ones, you know that!\n"
"VLADIMIR:\n"
"Then you don't want it?\n"
"ESTRAGON:\n"
"I only like the pink ones!\n"
"VLADIMIR:\n"
"Then give it back to me.\n"
"Estragon gives it back. ESTRAGON:\n"
"I'll go and get a carrot.\n"
"He does not move. VLADIMIR:\n"
"This is becoming really insignificant. ESTRAGON:\n"
"Not enough.\n"
"Silence. VLADIMIR:\n"
"What about trying them. ESTRAGON:\n"
"I've tried everything. VLADIMIR:\n"
"No, I mean the boots. ESTRAGON:\n"
"Would that be a good thing? VLADIMIR:\n"
"It'd pass the time. (Estragon hesitates.) I assure you, it'd be an occupation. ESTRAGON:\n"
"A relaxation. VLADIMIR:\n"
"A recreation. ESTRAGON:\n"
"A relaxation. VLADIMIR:\n"
"Try. ESTRAGON:\n"
"You'll help me? VLADIMIR:\n"
"I will of course. ESTRAGON:\n"
"We don't manage too badly, eh Didi, between the two of us? VLADIMIR:\n"
"Yes yes. Come on, we'll try the left first. ESTRAGON:\n"
"We always find something, eh Didi, to give us the impression we exist? VLADIMIR:\n"
"(impatiently). Yes yes, we're magicians. But let us persevere in what we have resolved, before we forget. (He picks up a boot.) Come on, give me your foot. (Estragon raises his foot.) The other, hog! (Estragon raises the other foot.) Higher! \n"
"  (Wreathed together they stagger about the stage. Vladimir succeeds finally in getting\n"
"on the boot.) Try and walk. (Estragon walks.) Well? ESTRAGON:\n"
"It fits. VLADIMIR:\n"
"(taking string from his pocket). We'll try and lace it. ESTRAGON:\n"
"(vehemently). No no, no laces, no laces! VLADIMIR:\n"
"You'll be sorry. Let's try the other. (As before.) Well? ESTRAGON:\n"
"(grudgingly). It fits too. VLADIMIR:\n"
"They don't hurt you? ESTRAGON:\n"
"Not yet. VLADIMIR:\n"
"Then you can keep them. ESTRAGON:\n"
"They're too big. VLADIMIR:\n"
"Perhaps you'll have socks some day. ESTRAGON:\n"
"True. VLADIMIR:\n"
"Then you'll keep them? ESTRAGON:\n"
"That's enough about these boots. VLADIMIR:\n"
"Yes, but— ESTRAGON:\n"
"(violently). Enough! (Silence.) I suppose I might as well sit down.\n"
"He looks for a place to sit down, then goes and sits down on the mound. VLADIMIR:\n"
"That's where you were sitting yesterday evening. ESTRAGON:\n"
"If I could only sleep. VLADIMIR:\n"
"Yesterday you slept. ESTRAGON:\n"
"I'll try.\n"
"He resumes his foetal posture, his head between his knees. VLADIMIR:\n"
"Wait. (He goes over and sits down beside Estragon and begins to sing in a loud voice.) Bye bye bye bye\n"
"Bye bye– \n"
"ESTRAGON:\n"
"(looking up angrily). Not so loud!\n"
"VLADIMIR: (softly).\n"
"Bye bye bye bye Bye bye bye bye Bye bye bye bye Bye bye ...\n"
"Estragon sleeps. Vladimir gets up softly, takes off his coat and lays it across Estragon's shoulders, then starts walking up and down, swinging his arms to keep himself warm. Estragon wakes with a start, jumps up, casts about wildly. Vladimir runs to him, puts his arms around him.) There ... there ... Didi is here ... don't be afraid ...\n"
"ESTRAGON: Ah!\n"
"VLADIMIR:\n"
"There ... there ... it's all over.\n"
"ESTRAGON:\n"
"I was falling—\n"
"VLADIMIR:\n"
"It's all over, it's all over.\n"
"ESTRAGON:\n"
"I was on top of a—\n"
"VLADIMIR:\n"
"Don't tell me! Come, we'll walk it off.\n"
"He takes Estragon by the arm and walks him up and down until Estragon refuses to go any further.\n"
"ESTRAGON:\n"
"That's enough. I'm tired.\n"
"VLADIMIR:\n"
"You'd rather be stuck there doing nothing?\n"
"ESTRAGON: Yes.\n"
"VLADIMIR:\n"
"Please yourself.\n"
"He releases Estragon, picks up his coat and puts it on. ESTRAGON:\n"
"Let's go. VLADIMIR:\n"
"We can't. ESTRAGON:\n"
"Why not? VLADIMIR:\n"
"We're waiting for Godot. ESTRAGON:\n"
"Ah! (Vladimir walks up and down.) Can you not stay still? VLADIMIR:\n"
"I'm cold. ESTRAGON:\n"
"We came too soon. VLADIMIR:\n"
"It's always at nightfall. ESTRAGON:\n"
"But night doesn't fall. VLADIMIR:\n"
"It'll fall all of a sudden, like yesterday. ESTRAGON:\n"
"Then it'll be night. VLADIMIR:\n"
"And we can go. ESTRAGON:\n"
"Then it'll be day again. (Pause. Despairing.) What'll we do, what'll we do! VLADIMIR:\n"
"(halting, violently). Will you stop whining! I've had about my bellyful of your\n"
"lamentations! ESTRAGON:\n"
"I'm going. VLADIMIR:\n"
"(seeing Lucky's hat). Well! ESTRAGON:\n"
"Farewell. VLADIMIR:\n"
"Lucky's hat. (He goes towards it.) I've been here an hour and never saw it. (Very\n"
"pleased.) Fine! ESTRAGON:\n"
"You'll never see me again. VLADIMIR:\n"
"I knew it was the right place. Now our troubles are over. (He picks up the hat, contemplates it, straightens it.) Must have been a very fine hat. (He puts it on in place of his own which he hands to Estragon.) Here.\n"
" ESTRAGON:\n"
"What? VLADIMIR:\n"
"Hold that.\n"
"Estragon takes Vladimir's hat. Vladimir adjusts Lucky's hat on his head. Estragon puts on Vladimir's hat in place of his own which he hands to Vladimir. Vladimir takes Estragon's hat. Estragon adjusts Vladimir's hat on his head. Vladimir puts on Estragon's hat in place of Lucky's which he hands to Estragon. Estragon takes Lucky's hat. Vladimir adjusts Estragon's hat on his head. Estragon puts on Lucky's hat in place of Vladimir's which he hands to Vladimir. Vladimir takes his hat, Estragon adjusts Lucky's hat on his head. Vladimir puts on his hat in place of Estragon's which he hands to Estragon. Estragon takes his hat. Vladimir adjusts his hat on his head. Estragon puts on his hat in place of Lucky's which he hands to Vladimir. Vladimir takes Lucky's hat. Estragon adjusts his hat on his head. Vladimir puts on Lucky's hat in place of his own which he hands to Estragon. Estragon takes Vladimir's hat. Vladimir adjusts Lucky's hat on his head. Estragon hands Vladimir's hat back to Vladimir who takes it and hands it back to Estragon who takes it and hands it back to Vladimir who takes it and throws it down.\n"
"How does it fit me?\n"
"ESTRAGON:\n"
"How would I know?\n"
"VLADIMIR:\n"
"No, but how do I look in it?\n"
"He turns his head coquettishly to and fro, minces like a mannequin.\n"
"ESTRAGON: Hideous.\n"
"VLADIMIR:\n"
"Yes, but not more so than usual?\n"
"ESTRAGON:\n"
"Neither more nor less.\n"
"VLADIMIR:\n"
"Then I can keep it. Mine irked me. (Pause.) How shall I say? (Pause.) It itched me. He takes off Lucky's hat, peers into it, shakes it, knocks on the crown, puts it on again.\n"
"ESTRAGON: I'm going.\n"
"Silence. VLADIMIR:\n"
"Will you not play? ESTRAGON:\n"
"Play at what? VLADIMIR:\n"
"We could play at Pozzo and Lucky. ESTRAGON:\n"
"Never heard of it. VLADIMIR:\n"
"I'll do Lucky, you do Pozzo. (He imitates Lucky sagging under the weight of his\n"
"baggage. Estragon looks at him with stupefaction.) Go on. ESTRAGON:\n"
"What am I to do? VLADIMIR:\n"
"Curse me! ESTRAGON:\n"
"(after reflection). Naughty! VLADIMIR:\n"
" Stronger!\n"
"ESTRAGON:\n"
"Gonococcus! Spirochete!\n"
"Vladimir sways back and forth, doubled in two.\n"
"VLADIMIR:\n"
"Tell me to think.\n"
"ESTRAGON: What?\n"
"VLADIMIR:\n"
"Say, Think, pig!\n"
"ESTRAGON: Think, pig!\n"
"Silence. VLADIMIR:\n"
"I can't. ESTRAGON:\n"
"That's enough of that. VLADIMIR:\n"
"Tell me to dance. ESTRAGON:\n"
"I'm going. VLADIMIR:\n"
"Dance, hog! (He writhes. Exit Estragon left, precipitately.) I can't! (He looks up, misses Estragon.) Gogo! (He moves wildly about the stage. Enter Estragon left, panting. He hastens towards Vladimir, falls into his arms.) There you are again at last!\n"
"ESTRAGON:\n"
"I'm accursed!\n"
"VLADIMIR:\n"
"Where were you? I thought you were gone for ever.\n"
"ESTRAGON: They're coming!\n"
"VLADIMIR: Who?\n"
"ESTRAGON:\n"
"I don't know.\n"
"VLADIMIR: How many?\n"
"ESTRAGON:\n"
"I don't know.\n"
"VLADIMIR:\n"
"(triumphantly). It's Godot! At last! Gogo! It's Godot! We're saved! Let's go and meet him! (He drags Estragon towards the wings. Estragon resists, pulls himself free, exit right.) Gogo! Come back! (Vladimir runs to extreme left, scans the horizon. Enter Estragon right, he hastens towards Vladimir, falls into his arms.) There you are again again!\n"
"ESTRAGON: I'm in hell!\n"
"VLADIMIR:\n"
"Where were you?\n"
"ESTRAGON:\n"
"They're coming there too!\n"
"VLADIMIR:\n"
"We're surrounded! (Estragon makes a rush towards back.) Imbecile! There's no way out there. (He takes Estragon by the arm and drags him towards front. Gesture towards front.) There! Not a soul in sight! Off you go! Quick! (He pushes Estragon towards\n"
"auditorium. Estragon recoils in horror.) You won't? (He contemplates auditorium.) Well I can understand that. Wait till I see. (He reflects.) Your only hope left is to disappear.\n"
"ESTRAGON: Where? VLADIMIR:\n"
"Behind the tree. (Estragon hesitates.) Quick! Behind the tree. (Estragon goes and crouches behind the tree, realizes he is not hidden, comes out from behind the tree.) Decidedly this tree will not have been the slightest use to us.\n"
"ESTRAGON:\n"
"(calmer). I lost my head. Forgive me. It won't happen again. Tell me what to do.\n"
"VLADIMIR:\n"
"There's nothing to do.\n"
"ESTRAGON:\n"
"You go and stand there. (He draws Vladimir to extreme right and places him with his back to the stage.) There, don't move, and watch out. (Vladimir scans horizon, screening his eyes with his hand. Estragon runs and takes up same position extreme left. They turn their heads and look at each other.) Back to back like in the good old days. (They continue to look at each other for a moment, then resume their watch. Long silence.) Do you see anything coming?\n"
"VLADIMIR:\n"
"(turning his head). What?\n"
"ESTRAGON:\n"
"(louder). Do you see anything coming?\n"
"VLADIMIR: No.\n"
"ESTRAGON: Nor I.\n"
"They resume their watch. Silence. VLADIMIR:\n"
"You must have had a vision. ESTRAGON:\n"
"(turning his head). What? VLADIMIR:\n"
"(louder). You must have had a vision. ESTRAGON:\n"
"No need to shout!\n"
"They resume their watch. Silence. VLADIMIR and ESTRAGON:\n"
"(turning simultaneously). Do you— VLADIMIR:\n"
"Oh pardon! ESTRAGON:\n"
"Carry on. VLADIMIR:\n"
"No no, after you. ESTRAGON:\n"
"No no, you first. VLADIMIR:\n"
"I interrupted you. ESTRAGON:\n"
"On the contrary.\n"
"They glare at each other angrily. VLADIMIR:\n"
"Ceremonious ape! ESTRAGON:\n"
"Punctilious pig! VLADIMIR:\n"
"Finish your phrase, I tell you! ESTRAGON:\n"
"Finish your own!\n"
"Silence. They draw closer, halt. VLADIMIR:\n"
"Moron! ESTRAGON:\n"
"That's the idea, let's abuse each other.\n"
"They turn, move apart, turn again and face each other. VLADIMIR:\n"
"Moron! ESTRAGON:\n"
"Vermin! VLADIMIR:\n"
"Abortion! ESTRAGON:\n"
"Morpion! VLADIMIR:\n"
"Sewer­rat! ESTRAGON:\n"
"Curate! VLADIMIR:\n"
"Cretin! ESTRAGON:\n"
"(with finality). Crritic! VLADIMIR:\n"
"Oh!\n"
"He wilts, vanquished, and turns away. ESTRAGON:\n"
"Now let's make it up. VLADIMIR:\n"
"Gogo! ESTRAGON:\n"
"Didi! VLADIMIR:\n"
"Your hand! ESTRAGON:\n"
"Take it! VLADIMIR:\n"
"Come to my arms! ESTRAGON:\n"
"Yours arms? VLADIMIR:\n"
"My breast! ESTRAGON:\n"
"Off we go! They embrace. \n"
"  They separate. Silence. VLADIMIR:\n"
"How time flies when one has fun!\n"
"Silence. ESTRAGON:\n"
"What do we do now? VLADIMIR:\n"
"While waiting. ESTRAGON:\n"
"While waiting.\n"
"Silence. VLADIMIR:\n"
"We could do our exercises. ESTRAGON:\n"
"Our movements. VLADIMIR:\n"
"Our elevations. ESTRAGON:\n"
"Our relaxations. VLADIMIR:\n"
"Our elongations. ESTRAGON:\n"
"Our relaxations. VLADIMIR:\n"
"To warm us up. ESTRAGON:\n"
"To calm us down. VLADIMIR:\n"
"Off we go.\n"
"Vladimir hops from one foot to the other. Estragon imitates him. ESTRAGON:\n"
"(stopping). That's enough. I'm tired. VLADIMIR:\n"
"(stopping). We're not in form. What about a little deep breathing? ESTRAGON:\n"
"I'm tired breathing.\n"
"VLADIMIR:\n"
"You're right. (Pause.) Let's just do the tree, for the balance.\n"
"ESTRAGON: The tree?\n"
"Vladimir does the tree, staggering about on one leg. VLADIMIR:\n"
"(stopping). Your turn.\n"
"Estragon does the tree, staggers. ESTRAGON:\n"
"Do you think God sees me? VLADIMIR:\n"
"You must close your eyes.\n"
"Estragon closes his eyes, staggers worse. ESTRAGON:\n"
"(stopping, brandishing his fists, at the top of his voice.) God have pity on me! VLADIMIR:\n"
"(vexed). And me? ESTRAGON:\n"
"On me! On me! Pity! On me!\n"
"Enter Pozzo and Lucky. Pozzo is blind. Lucky burdened as before. Rope as before, but much shorter, so that Pozzo may follow more easily. Lucky wearing a different hat. At the sight of Vladimir and Estragon he stops short. Pozzo, continuing on his way, bumps into him.\n"
"VLADIMIR: Gogo!\n"
"POZZO:\n"
"(clutching onto Lucky who staggers). What is it? Who is it?\n"
"Lucky falls, drops everything and brings down Pozzo with him. They lie helpless among the scattered baggage.\n"
"ESTRAGON:\n"
"Is it Godot?\n"
"VLADIMIR:\n"
"At last! (He goes towards the heap.) Reinforcements at last!\n"
"POZZO: Help!\n"
"ESTRAGON:\n"
"Is it Godot?\n"
"VLADIMIR:\n"
"We were beginning to weaken. Now we're sure to see the evening out.\n"
"POZZO: Help!\n"
"ESTRAGON:\n"
"Do you hear him?\n"
"VLADIMIR:\n"
"We are no longer alone, waiting for the night, waiting for Godot, waiting for ... waiting. All evening we have struggled, unassisted. Now it's over. It's already tomorrow.\n"
"POZZO: Help!\n"
"VLADIMIR:\n"
"Time flows again already. The sun will set, the moon rise, and we away ... from here.\n"
"POZZO: Pity!\n"
"VLADIMIR:\n"
"Poor Pozzo! ESTRAGON:\n"
"I knew it was him. VLADIMIR:\n"
"Who? ESTRAGON:\n"
"Godot. VLADIMIR:\n"
"But it's not Godot. ESTRAGON:\n"
"It's not Godot? VLADIMIR:\n"
"It's not Godot. ESTRAGON:\n"
"Then who is it? VLADIMIR:\n"
"It's Pozzo. POZZO:\n"
"Here! Here! Help me up! VLADIMIR:\n"
"He can't get up. ESTRAGON:\n"
"Let's go. VLADIMIR:\n"
"We can't. ESTRAGON:\n"
"Why not? VLADIMIR:\n"
"We're waiting for Godot. ESTRAGON:\n"
"Ah! VLADIMIR:\n"
"Perhaps he has another bone for you. ESTRAGON:\n"
"Bone? VLADIMIR:\n"
"Chicken. Do you not remember? ESTRAGON:\n"
"It was him? VLADIMIR:\n"
"Yes. ESTRAGON:\n"
"Ask him. VLADIMIR:\n"
"Perhaps we should help him first. ESTRAGON:\n"
"To do what? VLADIMIR:\n"
"To get up. ESTRAGON:\n"
"He can't get up? VLADIMIR:\n"
"He wants to get up. ESTRAGON:\n"
"Then let him get up. VLADIMIR:\n"
"He can't. ESTRAGON:\n"
"Why not? VLADIMIR:\n"
"I don't know.\n"
"Pozzo writhes, groans, beats the ground with his fists. ESTRAGON:\n"
"We should ask him for the bone first. Then if he refuses we'll leave him there. VLADIMIR:\n"
"You mean we have him at our mercy? ESTRAGON:\n"
"Yes. VLADIMIR:\n"
"And that we should subordinate our good offices to certain conditions? ESTRAGON:\n"
"What? VLADIMIR:\n"
"That seems intelligent all right. But there's one thing I'm afraid of. POZZO:\n"
"Help! ESTRAGON:\n"
"What? VLADIMIR:\n"
"That Lucky might get going all of a sudden. Then we'd be ballocksed. ESTRAGON:\n"
"Lucky? VLADIMIR:\n"
"The one that went for you yesterday. ESTRAGON:\n"
"I tell you there was ten of them. VLADIMIR:\n"
"No, before that, the one that kicked you. ESTRAGON:\n"
"Is he there? VLADIMIR:\n"
"As large as life. (Gesture towards Lucky.) For the moment he is inert. But he might run\n"
"amuck any minute. POZZO:\n"
"Help! ESTRAGON:\n"
"And suppose we gave him a good beating, the two of us. VLADIMIR:\n"
"You mean if we fell on him in his sleep? ESTRAGON:\n"
"Yes. VLADIMIR:\n"
"That seems a good idea all right. But could we do it? Is he really asleep? (Pause.) No,\n"
"the best would be to take advantage of Pozzo's calling for help— POZZO:\n"
"Help! VLADIMIR:\n"
" To help him—\n"
"ESTRAGON:\n"
"We help him?\n"
"VLADIMIR:\n"
"In anticipation of some tangible return.\n"
"ESTRAGON:\n"
"And suppose he—\n"
"VLADIMIR:\n"
"Let us not waste our time in idle discourse! (Pause. Vehemently.) Let us do something, while we have the chance! It is not every day that we are needed. Not indeed that we personally are needed. Others would meet the case equally well, if not better. To all mankind they were addressed, those cries for help still ringing in our ears! But at this place, at this moment of time, all mankind is us, whether we like it or not. Let us make the most of it, before it is too late! Let us represent worthily for once the foul brood to which a cruel fate consigned us! What do you say? (Estragon says nothing.) It is true that when with folded arms we weigh the pros and cons we are no less a credit to our species. The tiger bounds to the help of his congeners without the least reflection, or else he slinks away into the depths of the thickets. But that is not the question. What are we doing here, that is the question. And we are blessed in this, that we happen to know the answer. Yes, in this immense confusion one thing alone is clear. We are waiting for Godot to come—\n"
"ESTRAGON: Ah!\n"
"POZZO: Help!\n"
"VLADIMIR:\n"
"Or for night to fall. (Pause.) We have kept our appointment and that's an end to that. We are not saints, but we have kept our appointment. How many people can boast as much?\n"
"ESTRAGON: Billions.\n"
"VLADIMIR:\n"
"You think so?\n"
"ESTRAGON:\n"
"I don't know.\n"
"VLADIMIR:\n"
"You may be right.\n"
"POZZO: Help! \n"
"  VLADIMIR:\n"
"All I know is that the hours are long, under these conditions, and constrain us to beguile them with proceedings which –how shall I say– which may at first sight seem reasonable, until they become a habit. You may say it is to prevent our reason from foundering. No doubt. But has it not long been straying in the night without end of the abyssal depths? That's what I sometimes wonder. You follow my reasoning?\n"
"ESTRAGON:\n"
"(aphoristic for once). We are all born mad. Some remain so.\n"
"POZZO:\n"
"Help! I'll pay you!\n"
"ESTRAGON: How much?\n"
"POZZO:\n"
"One hundred francs!\n"
"ESTRAGON:\n"
"It's not enough.\n"
"VLADIMIR:\n"
"I wouldn't go so far as that.\n"
"ESTRAGON:\n"
"You think it's enough?\n"
"VLADIMIR:\n"
"No, I mean so far as to assert that I was weak in the head when I came into the world. But that is not the question.\n"
"POZZO:\n"
"Two hundred!\n"
"VLADIMIR:\n"
"We wait. We are bored. (He throws up his hand.) No, don't protest, we are bored to death, there's no denying it. Good. A diversion comes along and what do we do? We let it go to waste. Come, let's get to work! (He advances towards the heap, stops in his stride.) In an instant all will vanish and we'll be alone once more, in the midst of nothingness!\n"
"He broods.\n"
"POZZO:\n"
"Two hundred!\n"
"VLADIMIR:\n"
"We're coming!\n"
"He tries to pull Pozzo to his feet, fails, tries again, stumbles, falls, tries to get up, fails. ESTRAGON:\n"
"What's the matter with you all? VLADIMIR:\n"
"Help! ESTRAGON:\n"
"I'm going. VLADIMIR:\n"
"Don't leave me! They'll kill me! POZZO:\n"
"Where am I? VLADIMIR:\n"
"Gogo! POZZO:\n"
"Help! VLADIMIR:\n"
"Help! ESTRAGON:\n"
"I'm going. VLADIMIR:\n"
"Help me up first, then we'll go together. ESTRAGON:\n"
"You promise? VLADIMIR:\n"
"I swear it! ESTRAGON:\n"
"And we'll never come back? VLADIMIR:\n"
"Never! ESTRAGON:\n"
"We'll go to the Pyrenees. VLADIMIR:\n"
"Wherever you like. ESTRAGON:\n"
"I've always wanted to wander in the Pyrenees. VLADIMIR:\n"
"You'll wander in them. ESTRAGON:\n"
"(recoiling). Who farted? VLADIMIR:\n"
"Pozzo. POZZO:\n"
"Here! Here! Pity! ESTRAGON:\n"
"It's revolting! VLADIMIR:\n"
"Quick! Give me your hand! ESTRAGON:\n"
"I'm going. (Pause. Louder.) I'm going. VLADIMIR:\n"
"Well I suppose in the end I'll get up by myself. (He tries, fails.) In the fullness of time. ESTRAGON:\n"
" What's the matter with you?\n"
"VLADIMIR: Go to hell.\n"
"ESTRAGON:\n"
"Are you staying there?\n"
"VLADIMIR:\n"
"For the time being.\n"
"ESTRAGON:\n"
"Come on, get up, you'll catch a chill.\n"
"VLADIMIR:\n"
"Don't worry about me.\n"
"ESTRAGON:\n"
"Come on, Didi, don't be pig­headed!\n"
"He stretches out his hand which Vladimir makes haste to seize.\n"
"VLADIMIR: Pull!\n"
"Estragon pulls, stumbles, falls. Long silence. POZZO:\n"
"Help! VLADIMIR:\n"
"We've arrived. POZZO:\n"
"Who are you? VLADIMIR:\n"
"We are men.\n"
"Silence. ESTRAGON:\n"
"Sweet mother earth! VLADIMIR:\n"
"Can you get up? ESTRAGON:\n"
"I don't know. VLADIMIR:\n"
"Try. ESTRAGON:\n"
"Not now, not now.\n"
"Silence. POZZO:\n"
"What happened? VLADIMIR:\n"
"(violently). Will you stop it, you! Pest! He can think of nothing but himself! ESTRAGON:\n"
"What about a little snooze? VLADIMIR:\n"
"Did you hear him? He wants to know what happened! ESTRAGON:\n"
"Don't mind him. Sleep.\n"
"Silence. POZZO:\n"
"Pity! Pity! ESTRAGON:\n"
"(with a start). What is it? VLADIMIR:\n"
"Were you asleep? ESTRAGON:\n"
"I must have been. VLADIMIR:\n"
"It's this bastard Pozzo at it again. ESTRAGON:\n"
"Make him stop it. Kick him in the crotch. VLADIMIR:\n"
"(striking Pozzo). Will you stop it! Crablouse! (Pozzo extricates himself with cries of\n"
"pain and crawls away. He stops, saws the air blindly, calling for help. Vladimir,\n"
"propped on his elbow, observes his retreat.) He's off! (Pozzo collapses.) He's down!\n"
"\n"
"  ESTRAGON:\n"
"What do we do now?\n"
"VLADIMIR:\n"
"Perhaps I could crawl to him.\n"
"ESTRAGON:\n"
"Don't leave me!\n"
"VLADIMIR:\n"
"Or I could call to him.\n"
"ESTRAGON:\n"
"Yes, call to him.\n"
"VLADIMIR:\n"
"Pozzo! (Silence.) Pozzo! (Silence.) No reply.\n"
"ESTRAGON: Together.\n"
"VLADIMIR and ESTRAGON: Pozzo! Pozzo!\n"
"VLADIMIR: He moved.\n"
"ESTRAGON:\n"
"Are you sure his name is Pozzo?\n"
"VLADIMIR:\n"
"(alarmed). Mr. Pozzo! Come back! We won't hurt you! Silence.\n"
"ESTRAGON:\n"
"We might try him with other names.\n"
"VLADIMIR:\n"
"I'm afraid he's dying.\n"
"ESTRAGON:\n"
"It'd be amusing.\n"
"VLADIMIR:\n"
"What'd be amusing? ESTRAGON:\n"
"To try him with other names, one after the other. It'd pass the time. And we'd be bound\n"
"to hit on the right one sooner or later. VLADIMIR:\n"
"I tell you his name is Pozzo. ESTRAGON:\n"
"We'll soon see. (He reflects.) Abel! Abel! POZZO:\n"
"Help! ESTRAGON:\n"
"Got it in one! VLADIMIR:\n"
"I begin to weary of this motif. ESTRAGON:\n"
"Perhaps the other is called Cain. Cain! Cain! POZZO:\n"
"Help! ESTRAGON:\n"
"He's all humanity. (Silence.) Look at the little cloud. VLADIMIR:\n"
"(raising his eyes). Where? ESTRAGON:\n"
"There. In the zenith. VLADIMIR:\n"
"Well? (Pause.) What is there so wonderful about it?\n"
"Silence. ESTRAGON:\n"
"Let's pass on now to something else, do you mind? VLADIMIR:\n"
"I was just going to suggest it. ESTRAGON:\n"
"But to what? VLADIMIR:\n"
"Ah!\n"
"Silence. ESTRAGON:\n"
"Suppose we got up to begin with? VLADIMIR:\n"
"No harm trying.\n"
"They get up. ESTRAGON:\n"
"Child's play. VLADIMIR:\n"
"Simple question of will­power. ESTRAGON:\n"
"And now? POZZO:\n"
"Help! ESTRAGON: Let's go.\n"
"VLADIMIR: We can't.\n"
"ESTRAGON:\n"
"Why not? VLADIMIR:\n"
"We're waiting for Godot. ESTRAGON:\n"
"Ah! (Despairing.) What'll we do, what'll we do! POZZO:\n"
"Help! VLADIMIR:\n"
"What about helping him? ESTRAGON:\n"
"What does he want? VLADIMIR:\n"
"He wants to get up. ESTRAGON:\n"
"Then why doesn't he? VLADIMIR:\n"
"He wants us to help him get up. ESTRAGON:\n"
"Then why don't we? What are we waiting for?\n"
"They help Pozzo to his feet, let him go. He falls. VLADIMIR:\n"
"We must hold him. (They get him up again. Pozzo sags between them, his arms round their necks.) \n"
"Feeling better? POZZO:\n"
"Who are you? VLADIMIR:\n"
"Do you not recognize us? POZZO:\n"
"I am blind.\n"
"Silence. ESTRAGON:\n"
"Perhaps he can see into the future. VLADIMIR:\n"
"Since when? POZZO:\n"
"I used to have wonderful sight— but are you friends? ESTRAGON:\n"
"(laughing noisily). He wants to know if we are friends! VLADIMIR:\n"
"No, he means friends of his. ESTRAGON:\n"
"Well? VLADIMIR:\n"
"We've proved we are, by helping him. ESTRAGON:\n"
"Exactly. Would we have helped him if we weren't his friends? VLADIMIR:\n"
"Possibly. ESTRAGON:\n"
"True. VLADIMIR:\n"
"Don't let's quibble about that now. POZZO:\n"
"You are not highwaymen? ESTRAGON:\n"
"Highwaymen! Do we look like highwaymen? VLADIMIR:\n"
"Damn it, can't you see the man is blind! ESTRAGON:\n"
"Damn it, so he is. (Pause.) So he says. POZZO:\n"
"Don't leave me! VLADIMIR:\n"
"No question of it. ESTRAGON:\n"
"For the moment. POZZO:\n"
"What time is it? VLADIMIR:\n"
"(inspecting the sky). Seven o'clock ... eight o'clock ... ESTRAGON:\n"
"That depends what time of year it is. POZZO:\n"
"Is it evening?\n"
"Silence. Vladimir and Estragon scrutinize the sunset. ESTRAGON:\n"
"It's rising. VLADIMIR:\n"
"Impossible. ESTRAGON:\n"
"Perhaps it's the dawn. VLADIMIR:\n"
"Don't be a fool. It's the west over there. ESTRAGON:\n"
"How do you know? POZZO:\n"
"(anguished). Is it evening? VLADIMIR:\n"
"Anyway, it hasn't moved. ESTRAGON:\n"
"I tell you it's rising. POZZO:\n"
" Why don't you answer me?\n"
"ESTRAGON:\n"
"Give us a chance.\n"
"VLADIMIR:\n"
"(reassuring). It's evening, Sir, it's evening, night is drawing nigh. My friend here would have me doubt it and I must confess he shook me for a moment. But it is not for nothing I have lived through this long day and I can assure you it is very near the end of its repertory. (Pause.) How do you feel now?\n"
"ESTRAGON:\n"
"How much longer are we to cart him around? (They half release him, catch him again as he falls.) We are not caryatids!\n"
"VLADIMIR:\n"
"You were saying your sight used to be good, if I heard you right.\n"
"POZZO:\n"
"Wonderful! Wonderful, wonderful sight! Silence.\n"
"ESTRAGON:\n"
"(irritably). Expand! Expand!\n"
"VLADIMIR:\n"
"Let him alone. Can't you see he's thinking of the days when he was happy. (Pause.) Memoria praeteritorum bonorum— that must be unpleasant.\n"
"ESTRAGON:\n"
"We wouldn't know.\n"
"VLADIMIR:\n"
"And it came on you all of a sudden?\n"
"POZZO:\n"
"Quite wonderful!\n"
"VLADIMIR:\n"
"I'm asking you if it came on you all of a sudden.\n"
"POZZO:\n"
"I woke up one fine day as blind as Fortune. (Pause.) Sometimes I wonder if I'm not still asleep.\n"
"VLADIMIR:\n"
"And when was that?\n"
"POZZO:\n"
"I don't know.\n"
"VLADIMIR:\n"
"But no later than yesterday—\n"
"POZZO:\n"
"(violently). Don't question me! The blind have no notion of time. The things of time are hidden from them too.\n"
"VLADIMIR:\n"
"Well just fancy that! I could have sworn it was just the opposite.\n"
"ESTRAGON: I'm going.\n"
"POZZO:\n"
"Where are we?\n"
"VLADIMIR:\n"
"I couldn't tell you.\n"
"POZZO:\n"
"It isn't by any chance the place known as the Board?\n"
"VLADIMIR:\n"
"Never heard of it.\n"
"POZZO:\n"
"What is it like?\n"
"VLADIMIR:\n"
"(looking round). It's indescribable. It's like nothing. There's nothing. There's a tree.\n"
"POZZO:\n"
"Then it's not the Board.\n"
"ESTRAGON:\n"
"(sagging). Some diversion!\n"
"POZZO:\n"
"Where is my menial?\n"
"VLADIMIR:\n"
"He's about somewhere.\n"
"POZZO:\n"
"Why doesn't he answer when I call?\n"
"VLADIMIR:\n"
"I don't know. He seems to be sleeping. Perhaps he's dead.\n"
"POZZO:\n"
"What happened, exactly?\n"
"ESTRAGON: Exactly!\n"
"VLADIMIR:\n"
"The two of you slipped. (Pause.) And fell.\n"
"POZZO:\n"
"Go and see is he hurt.\n"
"VLADIMIR:\n"
"We can't leave you.\n"
"POZZO:\n"
"You needn't both go.\n"
"VLADIMIR:\n"
"(to Estragon). You go.\n"
"ESTRAGON:\n"
"After what he did to me? Never!\n"
"POZZO:\n"
"Yes yes, let your friend go, he stinks so. (Silence.) What is he waiting for?\n"
"VLADIMIR:\n"
"What are you waiting for?\n"
"ESTRAGON:\n"
"I'm waiting for Godot.\n"
"Silence. VLADIMIR:\n"
"What exactly should he do? POZZO:\n"
"Well to begin with he should pull on the rope, as hard as he likes so long as he doesn't strangle him. He usually responds to that. If not he should give him a taste of his boot, in the face and the privates as far as possible.\n"
"VLADIMIR:\n"
"(to Estragon). You see, you've nothing to be afraid of. It's even an opportunity to revenge yourself.\n"
"ESTRAGON:\n"
"And if he defends himself?\n"
"POZZO:\n"
"No no, he never defends himself.\n"
"VLADIMIR:\n"
"I'll come flying to the rescue.\n"
"ESTRAGON:\n"
"Don't take your eyes off me.\n"
"He goes towards Lucky. VLADIMIR:\n"
"Make sure he's alive before you start. No point in exerting yourself if he's dead. ESTRAGON:\n"
"(bending over Lucky). He's breathing. VLADIMIR:\n"
"Then let him have it.\n"
"With sudden fury Estragon starts kicking Lucky, hurling abuse at him as he does so. But he hurts his foot and moves away, limping and groaning. Lucky stirs.\n"
"ESTRAGON:\n"
"Oh the brute!\n"
"He sits down on the mound and tries to take off his boot. But he soon desists and\n"
"disposes himself for sleep, his arms on his knees and his head on his arms. POZZO:\n"
"What's gone wrong now? VLADIMIR:\n"
"My friend has hurt himself. POZZO:\n"
"And Lucky? VLADIMIR:\n"
"So it is he? POZZO:\n"
"What? VLADIMIR:\n"
"It is Lucky? POZZO:\n"
"I don't understand. VLADIMIR:\n"
"And you are Pozzo? POZZO:\n"
"Certainly I am Pozzo. VLADIMIR:\n"
"The same as yesterday? POZZO:\n"
"Yesterday? VLADIMIR:\n"
"We met yesterday. (Silence.) Do you not remember? POZZO:\n"
"I don't remember having met anyone yesterday. But tomorrow I won't remember having\n"
"met anyone today. So don't count on me to enlighten you. VLADIMIR:\n"
"But— POZZO:\n"
"Enough! Up pig! VLADIMIR:\n"
"You were bringing him to the fair to sell him. You spoke to us. He danced. He thought.\n"
"You had your sight. POZZO:\n"
"As you please. Let me go! (Vladimir moves away.) Up!\n"
"Lucky gets up, gathers up his burdens. VLADIMIR:\n"
"Where do you go from here? POZZO:\n"
"On. (Lucky, laden down, takes his place before Pozzo.) Whip! (Lucky puts everything down, looks for whip, finds it, puts it into Pozzo's hand, takes up everything again.) Rope!\n"
"Lucky puts everything down, puts end of rope into Pozzo's hand, takes up everything again.\n"
"VLADIMIR:\n"
"What is there in the bag?\n"
"POZZO:\n"
"Sand. (He jerks the rope.) On!\n"
"VLADIMIR: Don't go yet.\n"
"POZZO:\n"
"I'm going.\n"
"VLADIMIR:\n"
"What do you do when you fall far from help?\n"
"POZZO:\n"
"We wait till we can get up. Then we go on. On!\n"
"VLADIMIR:\n"
"Before you go tell him to sing.\n"
"POZZO: Who?\n"
"VLADIMIR: Lucky.\n"
"POZZO:\n"
"To sing?\n"
"VLADIMIR:\n"
"Yes. Or to think. Or to recite.\n"
"POZZO:\n"
"But he is dumb.\n"
"VLADIMIR: Dumb!\n"
"POZZO:\n"
"Dumb. He can't even groan.\n"
"VLADIMIR:\n"
"Dumb! Since when?\n"
"POZZO:\n"
"(suddenly furious.) Have you not done tormenting me with your accursed time! It's abominable! When! When! One day, is that not enough for you, one day he went dumb, one day I went blind, one day we'll go deaf, one day we were born, one day we shall die, the same day, the same second, is that not enough for you? (Calmer.) They give birth astride of a grave, the light gleams an instant, then it's night once more. (He jerks the rope.) On!\n"
"Exeunt Pozzo and Lucky. Vladimir follows them to the edge of the stage, looks after them. The noise of falling, reinforced by mimic of Vladimir, announces that they are down again. Silence. Vladimir goes towards Estragon, contemplates him a moment, then shakes him awake.\n"
"ESTRAGON:\n"
"(wild gestures, incoherent words. Finally.) Why will you never let me sleep?\n"
"VLADIMIR:\n"
"I felt lonely.\n"
"ESTRAGON:\n"
"I was dreaming I was happy.\n"
"VLADIMIR:\n"
"That passed the time.\n"
"ESTRAGON:\n"
"I was dreaming that—\n"
"VLADIMIR:\n"
"(violently). Don't tell me! (Silence.) I wonder is he really blind.\n"
"ESTRAGON: Blind? Who?\n"
"VLADIMIR: Pozzo.\n"
"ESTRAGON: Blind?\n"
"VLADIMIR:\n"
"He told us he was blind.\n"
"ESTRAGON:\n"
"Well what about it?\n"
"VLADIMIR:\n"
"It seemed to me he saw us.\n"
"ESTRAGON:\n"
"You dreamt it. (Pause.) Let's go. We can't. Ah! (Pause.) Are you sure it wasn't him?\n"
"VLADIMIR: Who?\n"
"ESTRAGON: Godot.\n"
"VLADIMIR: But who?\n"
"ESTRAGON: Pozzo.\n"
"VLADIMIR:\n"
"Not at all! (Less sure.) Not at all! (Still less sure.) Not at all!\n"
"ESTRAGON:\n"
"I suppose I might as well get up. (He gets up painfully.) Ow! Didi!\n"
"VLADIMIR:\n"
"I don't know what to think any more.\n"
"ESTRAGON:\n"
"My feet! (He sits down again and tries to take off his boots.) Help me!\n"
"VLADIMIR:\n"
"Was I sleeping, while the others suffered? Am I sleeping now? Tomorrow, when I wake, or think I do, what shall I say of today? That with Estragon my friend, at this place, until the fall of night, I waited for Godot? That Pozzo passed, with his carrier, and that he spoke to us? Probably. But in all that what truth will there be?\n"
"(Estragon, having struggled with his boots in vain, is dozing off again. Vladimir looks at him.) He'll know nothing. He'll tell me about the blows he received and I'll give him a carrot. (Pause.) Astride of a grave and a difficult birth. Down in the hole, lingeringly, the grave digger puts on the forceps. We have time to grow old. The air is full of our cries. (He listens.) But habit is a great deadener. (He looks again at Estragon.) At me too someone is looking, of me too someone is saying, He is sleeping, he knows nothing, let him sleep on. (Pause.) I can't go on! (Pause.) What have I said?\n"
"He goes feverishly to and fro, halts finally at extreme left, broods. Enter Boy right. He halts. Silence.\n"
"BOY:\n"
"Mister ... (Vladimir turns.) Mister Albert ...\n"
"VLADIMIR:\n"
"Off we go again. (Pause.) Do you not recognize me?\n"
"BOY:\n"
"No Sir.\n"
"VLADIMIR:\n"
"It wasn't you came yesterday.\n"
"BOY:\n"
"No Sir.\n"
"VLADIMIR:\n"
"This is your first time.\n"
"BOY:\n"
"Yes Sir.\n"
"Silence. VLADIMIR:\n"
"You have a message from Mr. Godot. BOY:\n"
"Yes Sir. VLADIMIR:\n"
"He won't come this evening. BOY:\n"
"No Sir. VLADIMIR:\n"
"But he'll come tomorrow. BOY:\n"
"Yes Sir. VLADIMIR:\n"
"Without fail. BOY:\n"
"Yes Sir.\n"
"Silence. VLADIMIR:\n"
"Did you meet anyone? BOY:\n"
"No Sir. VLADIMIR:\n"
"Two other ... (he hesitates) ... men? BOY:\n"
"I didn't see anyone, Sir.\n"
"Silence. VLADIMIR:\n"
"What does he do, Mr. Godot? (Silence.) Do you hear me? \n"
"BOY:\n"
"Yes Sir.\n"
"VLADIMIR: Well?\n"
"BOY:\n"
"He does nothing, Sir.\n"
"Silence. VLADIMIR:\n"
"How is your brother? BOY:\n"
"He's sick, Sir. VLADIMIR:\n"
"Perhaps it was he came yesterday. BOY:\n"
"I don't know, Sir.\n"
"Silence. VLADIMIR:\n"
"(softly). Has he a beard, Mr. Godot? BOY:\n"
"Yes Sir. VLADIMIR:\n"
"Fair or ... (he hesitates) ... or black? BOY:\n"
"I think it's white, Sir.\n"
"Silence. VLADIMIR:\n"
"Christ have mercy on us!\n"
"Silence. BOY:\n"
"What am I to tell Mr. Godot, Sir? VLADIMIR:\n"
"Tell him ... (he hesitates) ... tell him you saw me and that ... (he hesitates) ... that you saw me. (Pause. Vladimir advances, the Boy recoils. Vladimir halts, the Boy halts. With sudden violence.) You're sure you saw me, you won't come and tell me tomorrow that you never saw me!\n"
"Silence. Vladimir makes a sudden spring forward, the Boy avoids him and exits running. Silence. The sun sets, the moon rises. As in Act 1. Vladimir stands motionless and bowed. Estragon wakes, takes off his boots, gets up with one in each hand and goes and puts them down center front, then goes towards Vladimir.\n"
"ESTRAGON:\n"
"What's wrong with you?\n"
"VLADIMIR: Nothing. ESTRAGON:\n"
"I'm going. VLADIMIR:\n"
"So am I. ESTRAGON:\n"
"Was I long asleep? VLADIMIR:\n"
"I don't know.\n"
"Silence. ESTRAGON:\n"
" Where shall we go?\n"
"VLADIMIR: Not far.\n"
"ESTRAGON:\n"
"Oh yes, let's go far away from here.\n"
"VLADIMIR: We can't.\n"
"ESTRAGON: Why not?\n"
"VLADIMIR:\n"
"We have to come back tomorrow.\n"
"ESTRAGON: What for?\n"
"VLADIMIR:\n"
"To wait for Godot.\n"
"ESTRAGON:\n"
"Ah! (Silence.) He didn't come?\n"
"VLADIMIR: No.\n"
"ESTRAGON:\n"
"And now it's too late.\n"
"VLADIMIR:\n"
"Yes, now it's night.\n"
"ESTRAGON:\n"
"And if we dropped him? (Pause.) If we dropped him?\n"
"VLADIMIR:\n"
"He'd punish us. (Silence. He looks at the tree.) Everything's dead but the tree.\n"
"ESTRAGON:\n"
"(looking at the tree). What is it?\n"
"VLADIMIR:\n"
"It's the tree.\n"
"ESTRAGON:\n"
"Yes, but what kind?\n"
"VLADIMIR:\n"
"I don't know. A willow.\n"
"Estragon draws Vladimir towards the tree. They stand motionless before it. Silence. ESTRAGON:\n"
"Why don't we hang ourselves? VLADIMIR:\n"
"With what? ESTRAGON:\n"
"You haven't got a bit of rope? VLADIMIR:\n"
"No. ESTRAGON:\n"
"Then we can't.\n"
"Silence. VLADIMIR:\n"
"Let's go. ESTRAGON:\n"
"Wait, there's my belt. VLADIMIR:\n"
"It's too short. ESTRAGON:\n"
" You could hang onto my legs.\n"
"VLADIMIR:\n"
"And who'd hang onto mine?\n"
"ESTRAGON: True.\n"
"VLADIMIR:\n"
"Show me all the same. (Estragon loosens the cord that holds up his trousers which, much too big for him, fall about his ankles. They look at the cord.) It might do in a pinch. But is it strong enough?\n"
"ESTRAGON:\n"
"We'll soon see. Here.\n"
"They each take an end of the cord and pull. \n"
"It breaks. They almost fall. VLADIMIR:\n"
"Not worth a curse.\n"
"Silence. ESTRAGON:\n"
"You say we have to come back tomorrow? VLADIMIR:\n"
"Yes. ESTRAGON:\n"
"Then we can bring a good bit of rope. VLADIMIR:\n"
"Yes.\n"
"Silence. ESTRAGON:\n"
"Didi? VLADIMIR:\n"
"Yes. ESTRAGON:\n"
"I can't go on like this. VLADIMIR:\n"
"  That's what you think.\n"
"ESTRAGON:\n"
"If we parted? That might be better for us.\n"
"VLADIMIR:\n"
"We'll hang ourselves tomorrow. (Pause.) Unless Godot comes.\n"
"ESTRAGON:\n"
"And if he comes?\n"
"VLADIMIR:\n"
"We'll be saved.\n"
"Vladimir takes off his hat (Lucky's), peers inside it, feels about inside it, shakes it,\n"
" knocks on the crown, puts it on again. ESTRAGON:\n"
"Well? Shall we go? VLADIMIR:\n"
"Pull on your trousers. ESTRAGON:\n"
"What? VLADIMIR:\n"
"Pull on your trousers. ESTRAGON:\n"
"You want me to pull off my trousers? VLADIMIR:\n"
"Pull ON your trousers. ESTRAGON:\n"
"(realizing his trousers are down). True.\n"
"He pulls up his trousers. VLADIMIR:\n"
"Well? Shall we go? ESTRAGON:\n"
"Yes, let's go.\n"
"They do not move.\n"
"Curtain.\n";


