static const String hamletTitle[3] = {"Hamlet", "Soliloquy", "IV.iv.35-69"};
static const int hamletLength = 1509;
static const char hamlet[] PROGMEM =
"How all occasions do inform against me,/\n"
"And spur my dull revenge! What is a man,/\n"
"If his chief good and market of his time/\n"
"Be but to sleep and feed? a beast, no more./\n"
"Sure, he that made us with such large discourse,/\n"
"Looking before and after, gave us not/\n"
"That capability and god-like reason/\n"
"To fust in us unused. Now, whether it be/\n"
"Bestial oblivion, or some craven scruple/\n"
"Of thinking too precisely on the event,/\n"
"A thought which, quarter'd, hath but one part wisdom/\n"
"And ever three parts coward, I do not know/\n"
"Why yet I live to say 'This thing's to do;'/\n"
"Sith I have cause and will and strength and means/\n"
"To do't. Examples gross as earth exhort me:/\n"
"Witness this army of such mass and charge/\n"
"Led by a delicate and tender prince,/\n"
"Whose spirit with divine ambition puff'd/\n"
"Makes mouths at the invisible event,/\n"
"Exposing what is mortal and unsure/\n"
"To all that fortune, death and danger dare,/\n"
"Even for an egg-shell. Rightly to be great/\n"
"Is not to stir without great argument,/\n"
"But greatly to find quarrel in a straw/\n"
"When honour's at the stake. How stand I then,/\n"
"That have a father kill'd, a mother stain'd,/\n"
"Excitements of my reason and my blood,/\n"
"And let all sleep? while, to my shame, I see/\n"
"The imminent death of twenty thousand men,/\n"
"That, for a fantasy and trick of fame,/\n"
"Go to their graves like beds, fight for a plot/\n"
"Whereon the numbers cannot try the cause,/\n"
"Which is not tomb enough and continent/\n"
"To hide the slain? O, from this time forth,/\n"
"My thoughts be bloody, or be nothing worth!";
