//len with quotes + /n = 74856
//maybe len is 66073
//4-1774 lines = 1171 lines total = 4*1171 overcounted characters = 70172
static const String godot1Title[] = {"Waiting", "for Godot", "Act One"};
volatile static const int godot1Length = 66073;

static const char godot1[] PROGMEM = "Waiting for Godot tragicomedy in 2 acts\n"
"By Samuel Beckett\n"
"Estragon Vladimir Lucky Pozzo\n"
"a boy\n"
"A country road. A tree. Evening.\n"
"ACT I\n"
"Estragon, sitting on a low mound, is trying to take off his boot. He pulls at it with both hands, panting. \n"
"He gives up, exhausted, rests, tries again.\n"
"As before.\n"
"Enter Vladimir.\n"
"ESTRAGON:\n"
"\n"
"(giving up again). Nothing to be done.\n"
"VLADIMIR:\n"
"(advancing with short, stiff strides, legs wide apart). I'm beginning to come round to that opinion. All my life I've tried to put it from me, saying Vladimir, be reasonable, you haven't yet tried everything. And I resumed the struggle. (He broods, musing on the struggle. Turning to Estragon.) So there you are again. ESTRAGON:\n"
"Am I?\n"
"VLADIMIR:\n"
"I'm glad to see you back. I thought you were gone forever.\n"
"ESTRAGON:\n"
"Me too.\n"
"VLADIMIR:\n"
"Together again at last! We'll have to celebrate this. But how? (He reflects.) Get up till I embrace you.\n"
"ESTRAGON:\n"
"(irritably). Not now, not now.\n"
"VLADIMIR:\n"
"(hurt, coldly). May one inquire where His Highness spent the night? ESTRAGON:\n"
"In a ditch.\n"
"VLADIMIR:\n"
"(admiringly). A ditch! Where?\n"
"ESTRAGON:\n"
"(without gesture). Over there.\n"
"VLADIMIR:\n"
"And they didn't beat you?\n"
"ESTRAGON:\n"
"Beat me? Certainly they beat me.\n"
"VLADIMIR:\n"
"The same lot as usual?\n"
"ESTRAGON:\n"
"The same? I don't know.\n"
"VLADIMIR:\n"
"When I think of it ... all these years ... but for me ... where would you be ... (Decisively.) You'd be nothing more than a little heap of bones at the present minute, no doubt about it.\n"
"ESTRAGON:\n"
"And what of it?\n"
"VLADIMIR:\n"
"(gloomily). It's too much for one man. (Pause. Cheerfully.) On the other hand what's the good of losing heart now, that's what I say. We should have thought of it a million years ago, in the nineties.\n"
"ESTRAGON:\n"
"Ah stop blathering and help me off with this bloody thing.\n"
"VLADIMIR:\n"
"\n"
"Hand in hand from the top of the Eiffel Tower, among the first. We were respectable in those days. Now it's too late. They wouldn't even let us up. (Estragon tears at his boot.) What are you doing?\n"
"ESTRAGON:\n"
"Taking off my boot. Did that never happen to you?\n"
"VLADIMIR:\n"
"Boots must be taken off every day, I'm tired telling you that. Why don't you listen to me?\n"
"ESTRAGON:\n"
"(feebly). Help me!\n"
"VLADIMIR:\n"
"It hurts?\n"
"ESTRAGON:\n"
"(angrily). Hurts! He wants to know if it hurts!\n"
"VLADIMIR:\n"
"(angrily). No one ever suffers but you. I don't count. I'd like to hear what you'd say if you had what I have.\n"
"ESTRAGON:\n"
"It hurts?\n"
"VLADIMIR:\n"
"(angrily). Hurts! He wants to know if it hurts!\n"
"ESTRAGON:\n"
"(pointing). You might button it all the same.\n"
"VLADIMIR:\n"
"(stooping). True. (He buttons his fly.) Never neglect the little things of life. ESTRAGON:\n"
"What do you expect, you always wait till the last moment.\n"
"VLADIMIR:\n"
"(musingly). The last moment ... (He meditates.) Hope deferred maketh the something sick, who said that?\n"
"ESTRAGON:\n"
"Why don't you help me?\n"
"VLADIMIR:\n"
"Sometimes I feel it coming all the same. Then I go all queer. (He takes off his hat, peers inside it, feels about inside it, shakes it, puts it on again.) How shall I say? Relieved and at the same time ... (he searches for the word) ... appalled. (With emphasis.) AP-PALLED. (He takes off his hat again, peers inside it.) Funny. (He knocks on the crown as though to dislodge a foreign body, peers into it again, puts it on again.) Nothing to be done. (Estragon with a supreme effort succeeds in pulling off his boot. He peers inside it, feels about inside it, turns it upside down, shakes it, looks on the ground to see if anything has fallen out, finds nothing, feels inside it again, staring sightlessly before him.) Well?\n"
"ESTRAGON:\n"
"Nothing.\n"
"VLADIMIR:\n"
"Show me.\n"
"\n"
"ESTRAGON:\n"
"There's nothing to show.\n"
"VLADIMIR:\n"
"Try and put it on again.\n"
"ESTRAGON:\n"
"(examining his foot). I'll air it for a bit.\n"
"VLADIMIR:\n"
"There's man all over for you, blaming on his boots the faults of his feet. (He takes off his hat again, peers inside it, feels about inside it, knocks on the crown, blows into it, puts it on again.) This is getting alarming. (Silence. Vladimir deep in thought, Estragon pulling at his toes.) One of the thieves was saved. (Pause.) It's a reasonable percentage. (Pause.) Gogo.\n"
"ESTRAGON:\n"
"What?\n"
"VLADIMIR:\n"
"Suppose we repented.\n"
"ESTRAGON:\n"
"Repented what?\n"
"VLADIMIR:\n"
"Oh ... (He reflects.) We wouldn't have to go into the details.\n"
"ESTRAGON:\n"
"Our being born?\n"
"Vladimir breaks into a hearty laugh which he immediately stifles, his hand pressed to his pubis, his face contorted.\n"
"VLADIMIR:\n"
"One daren't even laugh any more.\n"
"ESTRAGON:\n"
"Dreadful privation.\n"
"VLADIMIR:\n"
"Merely smile. (He smiles suddenly from ear to ear, keeps smiling, ceases as suddenly.) It's not the same thing. Nothing to be done. (Pause.) Gogo. ESTRAGON:\n"
"(irritably). What is it?\n"
"VLADIMIR:\n"
"Did you ever read the Bible?\n"
"ESTRAGON:\n"
"The Bible ... (He reflects.) I must have taken a look at it.\n"
"VLADIMIR:\n"
"Do you remember the Gospels?\n"
"ESTRAGON:\n"
"I remember the maps of the Holy Land. Coloured they were. Very pretty. The Dead Sea was pale blue. The very look of it made me thirsty. That's where we'll go, I used to say, that's where we'll go for our honeymoon. We'll swim. We'll be happy.\n"
"VLADIMIR:\n"
"You should have been a poet.\n"
"\n"
"ESTRAGON:\n"
"I was. (Gesture towards his rags.) Isn't that obvious? Silence.\n"
"VLADIMIR:\n"
"Where was I ... How's your foot?\n"
"ESTRAGON:\n"
"Swelling visibly.\n"
"VLADIMIR:\n"
"Ah yes, the two thieves. Do you remember the story?\n"
"ESTRAGON:\n"
"No.\n"
"VLADIMIR:\n"
"Shall I tell it to you?\n"
"ESTRAGON:\n"
"No.\n"
"VLADIMIR:\n"
"It'll pass the time. (Pause.) Two thieves, crucified at the same time as our Saviour. One—\n"
"ESTRAGON:\n"
"Our what?\n"
"VLADIMIR:\n"
"Our Saviour. Two thieves. One is supposed to have been saved and the other ... (he searches for the contrary of saved) ... damned.\n"
"ESTRAGON:\n"
"Saved from what?\n"
"VLADIMIR:\n"
"Hell.\n"
"ESTRAGON:\n"
"I'm going.\n"
"He does not move.\n"
"VLADIMIR:\n"
"And yet ... (pause) ... how is it –this is not boring you I hope– how is it that of the four Evangelists only one speaks of a thief being saved. The four of them were there –or thereabouts– and only one speaks of a thief being saved. (Pause.) Come on, Gogo, return the ball, can't you, once in a way?\n"
"ESTRAGON:\n"
"(with exaggerated enthusiasm). I find this really most extraordinarily interesting. VLADIMIR:\n"
"One out of four. Of the other three, two don't mention any thieves at all and the third says that both of them abused him.\n"
"ESTRAGON:\n"
"Who?\n"
"VLADIMIR:\n"
"What?\n"
"ESTRAGON:\n"
"What's all this about? Abused who?\n"
"\n"
"VLADIMIR:\n"
"The Saviour.\n"
"ESTRAGON:\n"
"Why?\n"
"VLADIMIR:\n"
"Because he wouldn't save them.\n"
"ESTRAGON:\n"
"From hell?\n"
"VLADIMIR:\n"
"Imbecile! From death.\n"
"ESTRAGON:\n"
"I thought you said hell.\n"
"VLADIMIR:\n"
"From death, from death.\n"
"ESTRAGON:\n"
"Well what of it?\n"
"VLADIMIR:\n"
"Then the two of them must have been damned.\n"
"ESTRAGON:\n"
"And why not?\n"
"VLADIMIR:\n"
"But one of the four says that one of the two was saved.\n"
"ESTRAGON:\n"
"Well? They don't agree and that's all there is to it.\n"
"VLADIMIR:\n"
"But all four were there. And only one speaks of a thief being saved. Why believe him rather than the others?\n"
"ESTRAGON:\n"
"Who believes him?\n"
"VLADIMIR:\n"
"Everybody. It's the only version they know.\n"
"ESTRAGON:\n"
"People are bloody ignorant apes.\n"
"He rises painfully, goes limping to extreme left, halts, gazes into distance off with his hand screening his eyes, turns, goes to extreme right, gazes into distance. Vladimir watches him, then goes and picks up the boot, peers into it, drops it hastily.\n"
"VLADIMIR:\n"
"Pah!\n"
"He spits. Estragon moves to center, halts with his back to auditorium.\n"
"ESTRAGON:\n"
"Charming spot. (He turns, advances to front, halts facing auditorium.) Inspiring prospects. (He turns to Vladimir.) Let's go.\n"
"VLADIMIR:\n"
"We can't.\n"
"ESTRAGON:\n"
"\n"
"Why not?\n"
"VLADIMIR:\n"
"We're waiting for Godot.\n"
"ESTRAGON:\n"
"(despairingly). Ah! (Pause.) You're sure it was here? VLADIMIR:\n"
"What?\n"
"ESTRAGON:\n"
"That we were to wait.\n"
"VLADIMIR:\n"
"He said by the tree. (They look at the tree.) Do you see any others? ESTRAGON:\n"
"What is it?\n"
"VLADIMIR:\n"
"I don't know. A willow.\n"
"ESTRAGON:\n"
"Where are the leaves?\n"
"VLADIMIR:\n"
"It must be dead.\n"
"ESTRAGON:\n"
"No more weeping.\n"
"VLADIMIR:\n"
"Or perhaps it's not the season.\n"
"ESTRAGON:\n"
"Looks to me more like a bush.\n"
"VLADIMIR:\n"
"A shrub.\n"
"ESTRAGON:\n"
"A bush.\n"
"VLADIMIR:\n"
"A—. What are you insinuating? That we've come to the wrong place?\n"
"ESTRAGON:\n"
"He should be here.\n"
"VLADIMIR:\n"
"He didn't say for sure he'd come.\n"
"ESTRAGON:\n"
"And if he doesn't come?\n"
"VLADIMIR:\n"
"We'll come back tomorrow.\n"
"ESTRAGON:\n"
"And then the day after tomorrow.\n"
"VLADIMIR:\n"
"Possibly.\n"
"ESTRAGON:\n"
"And so on.\n"
"VLADIMIR:\n"
"\n"
"The point is—\n"
"ESTRAGON:\n"
"Until he comes.\n"
"VLADIMIR:\n"
"You're merciless.\n"
"ESTRAGON:\n"
"We came here yesterday.\n"
"VLADIMIR:\n"
"Ah no, there you're mistaken.\n"
"ESTRAGON:\n"
"What did we do yesterday?\n"
"VLADIMIR:\n"
"What did we do yesterday?\n"
"ESTRAGON:\n"
"Yes.\n"
"VLADIMIR:\n"
"Why ... (Angrily.) Nothing is certain when you're about. ESTRAGON:\n"
"In my opinion we were here.\n"
"VLADIMIR:\n"
"(looking round). You recognize the place? ESTRAGON:\n"
"I didn't say that.\n"
"VLADIMIR:\n"
"Well?\n"
"ESTRAGON:\n"
"That makes no difference.\n"
"VLADIMIR:\n"
"All the same ... that tree ... (turning towards auditorium) that bog ... ESTRAGON:\n"
"You're sure it was this evening?\n"
"VLADIMIR:\n"
"What?\n"
"ESTRAGON:\n"
"That we were to wait.\n"
"VLADIMIR:\n"
"He said Saturday. (Pause.) I think. ESTRAGON:\n"
"You think.\n"
"VLADIMIR:\n"
"I must have made a note of it. (He fumbles in his pockets, bursting with miscellaneous rubbish.)\n"
"ESTRAGON:\n"
"(very insidious). But what Saturday? And is it Saturday? Is it not rather Sunday? (Pause.) Or Monday? (Pause.) Or Friday?\n"
"VLADIMIR:\n"
"\n"
"(looking wildly about him, as though the date was inscribed in the landscape). It's not possible!\n"
"ESTRAGON:\n"
"Or Thursday?\n"
"VLADIMIR:\n"
"What'll we do?\n"
"ESTRAGON:\n"
"If he came yesterday and we weren't here you may be sure he won't come again today.\n"
"VLADIMIR:\n"
"But you say we were here yesterday.\n"
"ESTRAGON:\n"
"I may be mistaken. (Pause.) Let's stop talking for a minute, do you mind? VLADIMIR:\n"
"(feebly). All right. (Estragon sits down on the mound. Vladimir paces agitatedly to and fro, halting from time to time to gaze into distance off. Estragon falls asleep. Vladimir halts finally before Estragon.) Gogo! ... Gogo! ... GOGO! Estragon wakes with a start.\n"
"ESTRAGON:\n"
"(restored to the horror of his situation). I was asleep! (Despairingly.) Why will you never let me sleep?\n"
"VLADIMIR:\n"
"I felt lonely.\n"
"ESTRAGON:\n"
"I had a dream.\n"
"VLADIMIR:\n"
"Don't tell me!\n"
"ESTRAGON:\n"
"I dreamt that—\n"
"VLADIMIR:\n"
"DON'T TELL ME!\n"
"ESTRAGON:\n"
"(gesture toward the universe). This one is enough for you? (Silence.) It's not nice of you, Didi. Who am I to tell my private nightmares to if I can't tell them to you? VLADIMIR:\n"
"Let them remain private. You know I can't bear that.\n"
"ESTRAGON:\n"
"(coldly.) There are times when I wonder if it wouldn't be better for us to part. VLADIMIR:\n"
"You wouldn't go far.\n"
"ESTRAGON:\n"
"That would be too bad, really too bad. (Pause.) Wouldn't it, Didi, be really too bad? (Pause.) When you think of the beauty of the way. (Pause.) And the goodness of the wayfarers. (Pause. Wheedling.) Wouldn't it, Didi? VLADIMIR:\n"
"Calm yourself.\n"
"\n"
"ESTRAGON:\n"
"(voluptuously.) Calm ... calm ... The English say cawm. (Pause.) You know the story of the Englishman in the brothel?\n"
"VLADIMIR:\n"
"Yes.\n"
"ESTRAGON:\n"
"Tell it to me.\n"
"VLADIMIR:\n"
"Ah stop it!\n"
"ESTRAGON:\n"
"An Englishman having drunk a little more than usual proceeds to a brothel. The bawd asks him if he wants a fair one, a dark one or a red-haired one. Go on. VLADIMIR:\n"
"STOP IT!\n"
"Exit Vladimir hurriedly. Estragon gets up and follows him as far as the limit of the stage. Gestures of Estragon like those of a spectator encouraging a pugilist. Enter Vladimir. He brushes past Estragon, crosses the stage with bowed head. Estragon takes a step towards him, halts.\n"
"ESTRAGON:\n"
"(gently.) You wanted to speak to me? (Silence. Estragon takes a step forward.) You had something to say to me? (Silence. Another step forward.) Didi ... VLADIMIR:\n"
"(without turning). I've nothing to say to you.\n"
"ESTRAGON:\n"
"(step forward). You're angry? (Silence. Step forward). Forgive me. (Silence. Step forward. Estragon lays his hand on Vladimir's shoulder.) Come, Didi. (Silence.) Give me your hand. (Vladimir half turns.) Embrace me! (Vladimir stiffens.) Don't be stubborn! (Vladimir softens. They embrace. \n"
"Estragon recoils.) You stink of garlic!\n"
"VLADIMIR:\n"
"It's for the kidneys. (Silence. Estragon looks attentively at the tree.) What do we do now?\n"
"ESTRAGON:\n"
"Wait.\n"
"VLADIMIR:\n"
"Yes, but while waiting.\n"
"ESTRAGON:\n"
"What about hanging ourselves?\n"
"VLADIMIR:\n"
"Hmm. It'd give us an erection.\n"
"ESTRAGON:\n"
"(highly excited). An erection!\n"
"VLADIMIR:\n"
"With all that follows. Where it falls mandrakes grow. That's why they shriek when you pull them up. Did you not know that?\n"
"ESTRAGON:\n"
"\n"
"Let's hang ourselves immediately!\n"
"VLADIMIR:\n"
"From a bough? (They go towards the tree.) I wouldn't trust it. ESTRAGON:\n"
"We can always try.\n"
"VLADIMIR:\n"
"Go ahead.\n"
"ESTRAGON:\n"
"After you.\n"
"VLADIMIR:\n"
"No no, you first.\n"
"ESTRAGON:\n"
"Why me?\n"
"VLADIMIR:\n"
"You're lighter than I am.\n"
"ESTRAGON:\n"
"Just so!\n"
"VLADIMIR:\n"
"I don't understand.\n"
"ESTRAGON:\n"
"Use your intelligence, can't you?\n"
"Vladimir uses his intelligence.\n"
"VLADIMIR:\n"
"(finally). I remain in the dark.\n"
"ESTRAGON:\n"
"This is how it is. (He reflects.) The bough ... the bough ... (Angrily.) Use your head, can't you?\n"
"VLADIMIR:\n"
"You're my only hope.\n"
"ESTRAGON:\n"
"(with effort). Gogo light—bough not break—Gogo dead. Didi heavy—bough break—Didi alone. Whereas—\n"
"VLADIMIR:\n"
"I hadn't thought of that.\n"
"ESTRAGON:\n"
"If it hangs you it'll hang anything.\n"
"VLADIMIR:\n"
"But am I heavier than you?\n"
"ESTRAGON:\n"
"So you tell me. I don't know. There's an even chance. Or nearly.\n"
"VLADIMIR:\n"
"Well? What do we do?\n"
"ESTRAGON:\n"
"Don't let's do anything. It's safer.\n"
"VLADIMIR:\n"
"Let's wait and see what he says.\n"
"\n"
"ESTRAGON:\n"
"Who?\n"
"VLADIMIR:\n"
"Godot.\n"
"ESTRAGON:\n"
"Good idea.\n"
"VLADIMIR:\n"
"Let's wait till we know exactly how we stand.\n"
"ESTRAGON:\n"
"On the other hand it might be better to strike the iron before it freezes.\n"
"VLADIMIR:\n"
"I'm curious to hear what he has to offer. Then we'll take it or leave it.\n"
"ESTRAGON:\n"
"What exactly did we ask him for?\n"
"VLADIMIR:\n"
"Were you not there?\n"
"ESTRAGON:\n"
"I can't have been listening.\n"
"VLADIMIR:\n"
"Oh ... Nothing very definite.\n"
"ESTRAGON:\n"
"A kind of prayer.\n"
"VLADIMIR:\n"
"Precisely.\n"
"ESTRAGON:\n"
"A vague supplication.\n"
"VLADIMIR:\n"
"Exactly.\n"
"ESTRAGON:\n"
"And what did he reply?\n"
"VLADIMIR:\n"
"That he'd see.\n"
"ESTRAGON:\n"
"That he couldn't promise anything.\n"
"VLADIMIR:\n"
"That he'd have to think it over.\n"
"ESTRAGON:\n"
"In the quiet of his home.\n"
"VLADIMIR:\n"
"Consult his family.\n"
"ESTRAGON:\n"
"His friends.\n"
"VLADIMIR:\n"
"His agents.\n"
"ESTRAGON:\n"
"His correspondents.\n"
"\n"
"VLADIMIR:\n"
"His books.\n"
"ESTRAGON:\n"
"His bank account.\n"
"VLADIMIR:\n"
"Before taking a decision.\n"
"ESTRAGON:\n"
"It's the normal thing.\n"
"VLADIMIR:\n"
"Is it not?\n"
"ESTRAGON:\n"
"I think it is.\n"
"VLADIMIR:\n"
"I think so too.\n"
"Silence.\n"
"ESTRAGON:\n"
"(anxious). And we? VLADIMIR:\n"
"I beg your pardon? ESTRAGON:\n"
"I said, And we?\n"
"VLADIMIR:\n"
"I don't understand.\n"
"ESTRAGON:\n"
"Where do we come in?\n"
"VLADIMIR:\n"
"Come in?\n"
"ESTRAGON:\n"
"Take your time.\n"
"VLADIMIR:\n"
"Come in? On our hands and knees.\n"
"ESTRAGON:\n"
"As bad as that?\n"
"VLADIMIR:\n"
"Your Worship wishes to assert his prerogatives?\n"
"ESTRAGON:\n"
"We've no rights any more?\n"
"Laugh of Vladimir, stifled as before, less the smile.\n"
"VLADIMIR:\n"
"You'd make me laugh if it wasn't prohibited.\n"
"ESTRAGON:\n"
"We've lost our rights?\n"
"VLADIMIR:\n"
"(distinctly). We got rid of them.\n"
"Silence. They remain motionless, arms dangling, heads sunk, sagging at the knees.\n"
"\n"
"ESTRAGON:\n"
"(feebly). We're not tied? (Pause.) We're not— VLADIMIR:\n"
"Listen!\n"
"They listen, grotesquely rigid.  ESTRAGON:\n"
"I hear nothing.\n"
"VLADIMIR:\n"
"Hsst! (They listen. Estragon loses his balance, almost falls. He clutches the arm of Vladimir, who totters. They listen, huddled together.) Nor I.\n"
"Sighs of relief. They relax and separate.\n"
"ESTRAGON:\n"
"You gave me a fright.\n"
"VLADIMIR:\n"
"I thought it was he.\n"
"ESTRAGON:\n"
"Who?\n"
"VLADIMIR:\n"
"Godot.\n"
"ESTRAGON:\n"
"Pah! The wind in the reeds.\n"
"VLADIMIR:\n"
"I could have sworn I heard shouts.\n"
"ESTRAGON:\n"
"And why would he shout?\n"
"VLADIMIR:\n"
"At his horse.\n"
"Silence.\n"
"ESTRAGON:\n"
"(violently). I'm hungry! VLADIMIR:\n"
"Do you want a carrot? ESTRAGON:\n"
"Is that all there is?\n"
"VLADIMIR:\n"
"I might have some turnips.\n"
"ESTRAGON:\n"
"Give me a carrot. (Vladimir rummages in his pockets, takes out a turnip and gives it to Estragon who takes a bite out of it. Angrily.) It's a turnip!\n"
"VLADIMIR:\n"
"Oh pardon! I could have sworn it was a carrot. (He rummages again in his pockets, finds nothing but turnips.) All that's turnips. (He rummages.) You must have eaten the last. (He rummages.) Wait, I have it. (He brings out a carrot and gives it to Estragon.) There, dear fellow. \n"
"(Estragon wipes the carrot on his sleeve and begins to eat it.) Make it last, that's the end of them.\n"
"\n"
"ESTRAGON:\n"
"(chewing). I asked you a question. VLADIMIR:\n"
"Ah.\n"
"ESTRAGON:\n"
"Did you reply?\n"
"VLADIMIR:\n"
"How's the carrot?\n"
"ESTRAGON:\n"
"It's a carrot.\n"
"VLADIMIR:\n"
"So much the better, so much the better. (Pause.) What was it you wanted to know?\n"
"ESTRAGON:\n"
"I've forgotten. (Chews.) That's what annoys me. (He looks at the carrot appreciatively, dangles it between finger and thumb.) I'll never forget this carrot. (He sucks the end of it meditatively.) Ah yes, now I remember.\n"
"VLADIMIR:\n"
"Well?\n"
"ESTRAGON:\n"
"(his mouth full, vacuously). We're not tied? VLADIMIR:\n"
"I don't hear a word you're saying. ESTRAGON:\n"
"(chews, swallows). I'm asking you if we're tied. VLADIMIR:\n"
"Tied?\n"
"ESTRAGON:\n"
"Ti-ed.\n"
"VLADIMIR:\n"
"How do you mean tied?\n"
"ESTRAGON:\n"
"Down.\n"
"VLADIMIR:\n"
"But to whom? By whom?\n"
"ESTRAGON:\n"
"To your man.\n"
"VLADIMIR:\n"
"To Godot? Tied to Godot! What an idea! No question of it. (Pause.) For the moment.\n"
"ESTRAGON:\n"
"His name is Godot?\n"
"VLADIMIR:\n"
"I think so.\n"
"ESTRAGON:\n"
"\n"
"Fancy that. (He raises what remains of the carrot by the stub of leaf, twirls it before his eyes.) Funny, the more you eat the worse it gets.\n"
"VLADIMIR:\n"
"With me it's just the opposite.\n"
"ESTRAGON:\n"
"In other words?\n"
"VLADIMIR:\n"
"I get used to the muck as I go along.\n"
"ESTRAGON:\n"
"(after prolonged reflection). Is that the opposite? VLADIMIR:\n"
"Question of temperament.\n"
"ESTRAGON:\n"
"Of character.\n"
"VLADIMIR:\n"
"Nothing you can do about it.\n"
"ESTRAGON:\n"
"No use struggling.\n"
"VLADIMIR:\n"
"One is what one is.\n"
"ESTRAGON:\n"
"No use wriggling.\n"
"VLADIMIR:\n"
"The essential doesn't change.\n"
"ESTRAGON:\n"
"Nothing to be done. (He proffers the remains of the carrot to Vladimir.) Like to finish it?\n"
"A terrible cry, close at hand. Estragon drops the carrot. They remain motionless, then together make a sudden rush towards the wings. Estragon stops halfway, runs back, picks up the carrot, stuffs it in his pocket, runs to rejoin Vladimir who is waiting for him, stops again, runs back, picks up his boot, runs to rejoin Vladimir. Huddled together, shoulders hunched, cringing away from the menace, they wait. \n"
"Enter Pozzo and Lucky. Pozzo drives Lucky by means of a rope passed round his neck, so that Lucky is the first to enter, followed by the rope which is long enough to let him reach the middle of the stage before Pozzo appears. Lucky carries a heavy bag, a folding stool, a picnic basket and a greatcoat, Pozzo a whip. POZZO:\n"
"(off). On! (Crack of whip. Pozzo appears. They cross the stage. Lucky passes before Vladimir and Estragon and exit. Pozzo at the sight of Vladimir and Estragon stops short. The rope tautens. Pozzo jerks at it violently.) Back!\n"
"Noise of Lucky falling with all his baggage. Vladimir and Estragon turn towards him, half wishing half fearing to go to his assistance. Vladimir takes a step towards Lucky, Estragon holds him back by the sleeve.\n"
"VLADIMIR:\n"
"Let me go!\n"
"\n"
"ESTRAGON:\n"
"Stay where you are!\n"
"POZZO:\n"
"Be careful! He's wicked. (Vladimir and Estragon turn towards Pozzo.) With strangers.\n"
"ESTRAGON:\n"
"(undertone). Is that him?\n"
"VLADIMIR:\n"
"Who?\n"
"ESTRAGON:\n"
"(trying to remember the name). Er ... VLADIMIR:\n"
"Godot?\n"
"ESTRAGON:\n"
"Yes.\n"
"POZZO:\n"
"I present myself: Pozzo.\n"
"VLADIMIR:\n"
"(to Estragon). Not at all! ESTRAGON:\n"
"He said Godot. VLADIMIR:\n"
"Not at all!\n"
"ESTRAGON:\n"
"(timidly, to Pozzo). You're not Mr. Godot, Sir?\n"
"POZZO:\n"
"(terrifying voice). I am Pozzo! (Silence.) Pozzo! (Silence.) Does that name mean nothing to you? (Silence.) I say does that name mean nothing to you?\n"
"Vladimir and Estragon look at each other questioningly.\n"
"ESTRAGON:\n"
"(pretending to search). Bozzo ... Bozzo ...\n"
"VLADIMIR:\n"
"(ditto). Pozzo ... Pozzo ...\n"
"POZZO:\n"
"PPPOZZZO!\n"
"ESTRAGON:\n"
"Ah! Pozzo ... let me see ... Pozzo ...\n"
"VLADIMIR:\n"
"Is it Pozzo or Bozzo?\n"
"ESTRAGON:\n"
"Pozzo ... no ... I'm afraid I ... no ... I don't seem to ...\n"
"Pozzo advances threateningly.\n"
"VLADIMIR:\n"
"(conciliating). I once knew a family called Gozzo. The mother had the clap. ESTRAGON:\n"
"(hastily). We're not from these parts, Sir.\n"
"\n"
"POZZO:\n"
"(halting). You are human beings none the less. (He puts on his glasses.) As far as one can see. (He takes off his glasses.) Of the same species as myself. (He bursts into an enormous laugh.) Of the same species as Pozzo! Made in God's image! VLADIMIR:\n"
"Well you see—\n"
"POZZO:\n"
"(peremptory). Who is Godot? ESTRAGON:\n"
"Godot?\n"
"POZZO:\n"
"You took me for Godot.\n"
"VLADIMIR:\n"
"Oh no, Sir, not for an instant, Sir.\n"
"POZZO:\n"
"Who is he?\n"
"VLADIMIR:\n"
"Oh he's a ... he's a kind of acquaintance.\n"
"ESTRAGON:\n"
"Nothing of the kind, we hardly know him.\n"
"VLADIMIR:\n"
"True ... we don't know him very well ... but all the same ...\n"
"ESTRAGON:\n"
"Personally, I wouldn't even know him if I saw him.\n"
"POZZO:\n"
"You took me for him.\n"
"ESTRAGON:\n"
"(recoiling before Pozzo). That's to say ... you understand ... the dusk ... the strain ... waiting ... I confess ... I imagined ... for a second ...\n"
"POZZO:\n"
"Waiting? So you were waiting for him?\n"
"VLADIMIR:\n"
"Well you see—\n"
"POZZO:\n"
"Here? On my land?\n"
"VLADIMIR:\n"
"We didn't intend any harm.\n"
"ESTRAGON:\n"
"We meant well.\n"
"POZZO:\n"
"The road is free to all.\n"
"VLADIMIR:\n"
"That's how we looked at it.\n"
"POZZO:\n"
"It's a disgrace. But there you are.\n"
"ESTRAGON:\n"
"\n"
"Nothing we can do about it.\n"
"POZZO:\n"
"(with magnanimous gesture). Let's say no more about it. (He jerks the rope.) Up pig! (Pause.) Every time he drops he falls asleep. (Jerks the rope.) Up hog! (Noise of Lucky getting up and picking up his baggage. Pozzo jerks the rope.) Back! (Enter Lucky backwards.) Stop! (Lucky stops.) Turn! (Lucky turns. To Vladimir and Estragon, affably.) Gentlemen, I am happy to have met you. (Before their incredulous expression.) Yes yes, sincerely happy. (He jerks the rope.) Closer! (Lucky advances.) Stop! (Lucky stops.) Yes, the road seems long when one journeys all alone for ... (he consults his watch) ... yes ... (he calculates) ... yes, six hours, that's right, six hours on end, and never a soul in sight. (To Lucky.) Coat! (Lucky puts down the bag, advances, gives the coat, goes back to his place, takes up the bag.) Hold that! (Pozzo holds out the whip. Lucky advances and, both his hands being occupied, takes the whip in his mouth, then goes back to his place. Pozzo begins to put on his coat, stops.) Coat! (Lucky puts down the bag, basket and stool, helps Pozzo on with his coat, goes back to his place and takes up bag, basket and stool.) Touch of autumn in the air this evening. (Pozzo finishes buttoning up his coat, stoops, inspects himself, straightens up.) Whip! (Lucky advances, stoops, Pozzo snatches the whip from his mouth, Lucky goes back to his place.) Yes, gentlemen, I cannot go for long without the society of my likes (he puts on his glasses and looks at the two likes) even when the likeness is an imperfect one. (He takes off his glasses.) Stool! (Lucky puts down bag and basket, advances, opens stool, puts it down, goes back to his place, takes up bag and basket.) Closer! (Lucky puts down bag and basket, advances, moves stool, goes back to his place, takes up bag and basket. Pozzo sits down, places the butt of his whip against Lucky's chest and pushes.) Back! (Lucky takes a step back.) Further! (Lucky takes another step back.) Stop! (Lucky stops. To Vladimir and Estragon.) That is why, with your permission, I propose to dally with you a moment, before I venture any further. Basket! (Lucky advances, gives the basket, goes back to his place.) The fresh air stimulates the jaded appetite. (He opens the basket, takes out a piece of chicken and a bottle of wine.) Basket! (Lucky advances, picks up the basket and goes back to his place.) Further! (Lucky takes a step back.) He stinks. Happy days!\n"
"He drinks from the bottle, puts it down and begins to eat. Silence. \n"
"Vladimir and Estragon, cautiously at first, then more boldly, begin to circle about Lucky, inspecting him up and down. Pozzo eats his chicken voraciously, throwing away the bones after having sucked them. Lucky sags slowly, until bag and basket touch the ground, then straightens up with a start and begins to sag again. Rhythm of one sleeping on his feet.\n"
"ESTRAGON:\n"
"What ails him?\n"
"VLADIMIR:\n"
"He looks tired.\n"
"ESTRAGON:\n"
"Why doesn't he put down his bags?\n"
"VLADIMIR:\n"
"\n"
"How do I know? (They close in on him.) Careful! ESTRAGON:\n"
"Say something to him.\n"
"VLADIMIR:\n"
"Look!\n"
"ESTRAGON:\n"
"What?\n"
"VLADIMIR:\n"
"(pointing). His neck!\n"
"ESTRAGON:\n"
"(looking at the neck). I see nothing.\n"
"VLADIMIR:\n"
"Here.\n"
"Estragon goes over beside Vladimir.\n"
"ESTRAGON:\n"
"Oh I say!\n"
"VLADIMIR:\n"
"A running sore!\n"
"ESTRAGON:\n"
"It's the rope.\n"
"VLADIMIR:\n"
"It's the rubbing.\n"
"ESTRAGON:\n"
"It's inevitable.\n"
"VLADIMIR:\n"
"It's the knot.\n"
"ESTRAGON:\n"
"It's the chafing.\n"
"They resume their inspection, dwell on the face. VLADIMIR:\n"
"(grudgingly). He's not bad looking.\n"
"ESTRAGON:\n"
"(shrugging his shoulders, wry face.) Would you say so? VLADIMIR:\n"
"A trifle effeminate.\n"
"ESTRAGON:\n"
"Look at the slobber.\n"
"VLADIMIR:\n"
"It's inevitable.\n"
"ESTRAGON:\n"
"Look at the slaver.\n"
"VLADIMIR:\n"
"Perhaps he's a halfwit.\n"
"ESTRAGON:\n"
"A cretin.\n"
"VLADIMIR:\n"
"\n"
"(looking closer). Looks like a goiter. ESTRAGON:\n"
"(ditto). It's not certain. VLADIMIR:\n"
"He's panting.\n"
"ESTRAGON:\n"
"It's inevitable.\n"
"VLADIMIR:\n"
"And his eyes!\n"
"ESTRAGON:\n"
"What about them?\n"
"VLADIMIR:\n"
"Goggling out of his head.  ESTRAGON:\n"
"Looks like his last gasp to me. VLADIMIR:\n"
"It's not certain. (Pause.) Ask him a question. ESTRAGON:\n"
"Would that be a good thing?\n"
"VLADIMIR:\n"
"What do we risk?\n"
"ESTRAGON:\n"
"(timidly). Mister ... VLADIMIR: Louder. ESTRAGON: (louder). Mister ... POZZO:\n"
"Leave him in peace! (They turn toward Pozzo who, having finished eating, wipes his mouth with the back of his hand.) Can't you see he wants to rest? Basket! (He strikes a match and begins to light his pipe. Estragon sees the chicken bones on the ground and stares at them greedily. As Lucky does not move Pozzo throws the match angrily away and jerks the rope.) Basket! (Lucky starts, almost falls, recovers his senses, advances, puts the bottle in the basket and goes back to his place. Estragon stares at the bones. Pozzo strikes another match and lights his pipe.) What can you expect, it's not his job. (He pulls at his pipe, stretches out his legs.) Ah! That's better.\n"
"ESTRAGON:\n"
"(timidly). Please Sir ... POZZO:\n"
"What is it, my good man? ESTRAGON:\n"
"Er ... you've finished with the ... er ... you don't need the ... er ... bones, Sir?\n"
"VLADIMIR:\n"
"(scandalized). You couldn't have waited? POZZO:\n"
"\n"
"No no, he does well to ask. Do I need the bones? (He turns them over with the end of his whip.) No, personally I do not need them any more. (Estragon takes a step towards the bones.) But ... (Estragon stops short) ... but in theory the bones go to the carrier. He is therefore the one to ask. (Estragon turns towards Lucky, hesitates.) Go on, go on, don't be afraid, ask him, he'll tell you.\n"
"Estragon goes towards Lucky, stops before him.\n"
"ESTRAGON:\n"
"Mister ... excuse me, Mister ...\n"
"POZZO:\n"
"You're being spoken to, pig! Reply! (To Estragon.) Try him again. ESTRAGON:\n"
"Excuse me, Mister, the bones, you won't be wanting the bones? Lucky looks long at Estragon.\n"
"POZZO:\n"
"(in raptures). Mister! (Lucky bows his head.) Reply! Do you want them or don't you? (Silence of Lucky. To Estragon.) They're yours. (Estragon makes a dart at the bones, picks them up and begins to gnaw them.) I don't like it. I've never known him to refuse a bone before. (He looks anxiously at Lucky.) Nice business it'd be if he fell sick on me!\n"
"He puffs at his pipe.\n"
"VLADIMIR:\n"
"(exploding). It's a scandal!\n"
"Silence. Flabbergasted, Estragon stops gnawing, looks at Pozzo and Vladimir in turn. Pozzo outwardly calm. Vladimir embarrassed.\n"
"POZZO:\n"
"(To Vladimir). Are you alluding to anything in particular?\n"
"VLADIMIR:\n"
"(stutteringly resolute). To treat a man ... (gesture towards Lucky) ... like that ... I think that ... no ... a human being ... no ... it's a scandal!\n"
"ESTRAGON:\n"
"(not to be outdone). A disgrace!\n"
"He resumes his gnawing.\n"
"POZZO:\n"
"You are severe. (To Vladimir.) What age are you, if it's not a rude question? (Silence.) Sixty? Seventy? (To Estragon.) What age would you say he was? ESTRAGON:\n"
"Eleven.\n"
"POZZO:\n"
"I am impertinent. (He knocks out his pipe against the whip, gets up.) I must be getting on. Thank you for your society. (He reflects.) Unless I smoke another pipe before I go. What do you say? (They say nothing.) Oh I'm only a small smoker, a very small smoker, I'm not in the habit of smoking two pipes one on top of the other, it makes (hand to heart, sighing) my heart go pit-a-pat. (Silence.) It's the nicotine, one absorbs it in spite of one's precautions. (Sighs.) You know how it is. (Silence.) But perhaps you don't smoke? Yes? No? It's of no importance. (Silence.) But how am I to sit down now, without affectation, now that I have\n"
"\n"
"risen? Without appearing to –how shall I say– without appearing to falter. (To Vladimir.) I beg your pardon? (Silence.) Perhaps you didn't speak? (Silence.) It's of no importance. Let me see ...\n"
"He reflects.\n"
"ESTRAGON:\n"
"Ah! That's better.\n"
"He puts the bones in his pocket.\n"
"VLADIMIR:\n"
"Let's go.\n"
"ESTRAGON:\n"
"So soon?\n"
"POZZO:\n"
"One moment! (He jerks the rope.) Stool! (He points with his whip. Lucky moves the stool.) More! There! (He sits down. Lucky goes back to his place.) Done it! He fills his pipe.\n"
"VLADIMIR:\n"
"(vehemently). Let's go!\n"
"POZZO:\n"
"I hope I'm not driving you away. Wait a little longer, you'll never regret it. ESTRAGON:\n"
"(scenting charity). We're in no hurry.\n"
"POZZO:\n"
"(having lit his pipe). The second is never so sweet ... (he takes the pipe out of his mouth, contemplates it) ... as the first I mean. (He puts the pipe back in his mouth.) But it's sweet just the same.\n"
"VLADIMIR:\n"
"I'm going.\n"
"POZZO:\n"
"He can no longer endure my presence. I am perhaps not particularly human, but who cares? (To Vladimir.) Think twice before you do anything rash. Suppose you go now while it is still day, for there is no denying it is still day. (They all look up at the sky.) Good. (They stop looking at the sky.) What happens in that case– (he takes the pipe out of his mouth, examines it) –I'm out– (he relights his pipe) –in that case– (puff) –in that case– (puff) –what happens in that case to your appointment with this ... Godet ... Godot ... Godin ... anyhow you see who I mean, who has your future in his hands ... (pause) ... at least your immediate future?\n"
"VLADIMIR:\n"
"Who told you?\n"
"POZZO:\n"
"He speaks to me again! If this goes on much longer we'll soon be old friends. ESTRAGON:\n"
"Why doesn't he put down his bags?\n"
"POZZO:\n"
"I too would be happy to meet him. The more people I meet the happier I become. From the meanest creature one departs wiser, richer, more conscious of one's\n"
"\n"
"blessings. Even you ... (he looks at them ostentatiously in turn to make it clear they are both meant) ... even you, who knows, will have added to my store. ESTRAGON:\n"
"Why doesn't he put down his bags?\n"
"POZZO:\n"
"But that would surprise me.\n"
"VLADIMIR:\n"
"You're being asked a question.\n"
"POZZO:\n"
"(delighted). A question! Who? What? A moment ago you were calling me Sir, in fear and trembling. Now you're asking me questions. No good will come of this! VLADIMIR:\n"
"(to Estragon). I think he's listening.\n"
"ESTRAGON:\n"
"(circling about Lucky). What?\n"
"VLADIMIR:\n"
"You can ask him now. He's on the alert.\n"
"ESTRAGON:\n"
"Ask him what?\n"
"VLADIMIR:\n"
"Why he doesn't put down his bags.\n"
"ESTRAGON:\n"
"I wonder.\n"
"VLADIMIR:\n"
"Ask him, can't you?\n"
"POZZO:\n"
"(who has followed these exchanges with anxious attention, fearing lest the question get lost). You want to know why he doesn't put down his bags, as you call them.\n"
"VLADIMIR:\n"
"That's it.\n"
"POZZO:\n"
"(to Estragon). You are sure you agree with that?\n"
"ESTRAGON:\n"
"He's puffing like a grampus.\n"
"POZZO:\n"
"The answer is this. (To Estragon). But stay still, I beg of you, you're making me nervous!\n"
"VLADIMIR:\n"
"Here.\n"
"ESTRAGON:\n"
"What is it?\n"
"VLADIMIR:\n"
"He's about to speak.\n"
"Estragon goes over beside Vladimir. Motionless, side by side, they wait. POZZO:\n"
"\n"
"Good. Is everybody ready? Is everybody looking at me? (He looks at Lucky, jerks the rope. Lucky raises his head.) Will you look at me, pig! (Lucky looks at him.) Good. (He puts the pipe in his pocket, takes out a little vaporizer and sprays his throat, puts back the vaporizer in his pocket, clears his throat, spits, takes out the vaporizer again, sprays his throat again, puts back the vaporizer in his pocket.) I am ready. Is everybody listening? Is everybody ready? (He looks at them all in turn, jerks the rope.) Hog! (Lucky raises his head.) I don't like talking in a vacuum. Good. Let me see.\n"
"He reflects.\n"
"ESTRAGON:\n"
"I'm going.\n"
"POZZO:\n"
"What was it exactly you wanted to know?\n"
"VLADIMIR:\n"
"Why he—\n"
"POZZO:\n"
"(angrily). Don't interrupt me! (Pause. Calmer.) If we all speak at once we'll never get anywhere. (Pause.) What was I saying? (Pause. Louder.) What was I saying? Vladimir mimics one carrying a heavy burden. Pozzo looks at him, puzzled. ESTRAGON:\n"
"(forcibly). Bags. (He points at Lucky.) Why? Always hold. (He sags, panting.) Never put down. (He opens his hands, straightens up with relief.) Why? POZZO:\n"
"Ah! Why couldn't you say so before? Why he doesn't make himself comfortable? Let's try and get this clear. Has he not the right to? Certainly he has. It follows that he doesn't want to. There's reasoning for you. And why doesn't he want to? (Pause.) Gentlemen, the reason is this.\n"
"VLADIMIR:\n"
"(to Estragon). Make a note of this.\n"
"POZZO:\n"
"He wants to impress me, so that I'll keep him.\n"
"ESTRAGON:\n"
"What?\n"
"POZZO:\n"
"Perhaps I haven't got it quite right. He wants to mollify me, so that I'll give up the idea of parting with him. No, that's not exactly it either.\n"
"VLADIMIR:\n"
"You want to get rid of him?\n"
"POZZO:\n"
"He wants to cod me, but he won't.\n"
"VLADIMIR:\n"
"You want to get rid of him?\n"
"POZZO:\n"
"He imagines that when I see how well he carries I'll be tempted to keep him on in that capacity.\n"
"ESTRAGON:\n"
"\n"
"You've had enough of him?\n"
"POZZO:\n"
"In reality he carries like a pig. It's not his job.\n"
"VLADIMIR:\n"
"You want to get rid of him?\n"
"POZZO:\n"
"He imagines that when I see him indefatigable I'll regret my decision. Such is his miserable scheme. As though I were short of slaves! (All three look at Lucky.) Atlas, son of Jupiter! (Silence.) Well, that's that, I think. Anything else? Vaporizer.\n"
"VLADIMIR:\n"
"You want to get rid of him?\n"
"POZZO:\n"
"Remark that I might just as well have been in his shoes and he in mine. If chance had not willed otherwise. To each one his due.\n"
"VLADIMIR:\n"
"You waagerrim?\n"
"POZZO:\n"
"I beg your pardon?\n"
"VLADIMIR:\n"
"You want to get rid of him?\n"
"POZZO:\n"
"I do. But instead of driving him away as I might have done, I mean instead of simply kicking him out on his arse, in the goodness of my heart I am bringing him to the fair, where I hope to get a good price for him. The truth is you can't drive such creatures away. The best thing would be to kill them.\n"
"Lucky weeps.\n"
"ESTRAGON:\n"
"He's crying!\n"
"POZZO:\n"
"Old dogs have more dignity. (He proffers his handkerchief to Estragon.) Comfort him, since you pity him. (Estragon hesitates.) Come on. (Estragon takes the handkerchief.) Wipe away his tears, he'll feel less forsaken.\n"
"Estragon hesitates.\n"
"VLADIMIR:\n"
"Here, give it to me, I'll do it.\n"
"Estragon refuses to give the handkerchief.\n"
"Childish gestures.\n"
"POZZO:\n"
"Make haste, before he stops. (Estragon approaches Lucky and makes to wipe his eyes. Lucky kicks him violently in the shins. Estragon drops the handkerchief, recoils, staggers about the stage howling with pain.) Hanky!\n"
"Lucky puts down bag and basket, picks up handkerchief and gives it to Pozzo, goes back to his place, picks up bag and basket.\n"
"ESTRAGON:\n"
"Oh the swine! (He pulls up the leg of his trousers.) He's crippled me!\n"
"\n"
"POZZO:\n"
"I told you he didn't like strangers.\n"
"VLADIMIR:\n"
"(to Estragon). Show me. (Estragon shows his leg. To Pozzo, angrily.) He's bleeding!\n"
"POZZO:\n"
"It's a good sign.\n"
"ESTRAGON:\n"
"(on one leg). I'll never walk again!\n"
"VLADIMIR:\n"
"(tenderly). I'll carry you. (Pause.) If necessary.\n"
"POZZO:\n"
"He's stopped crying. (To Estragon.) You have replaced him as it were. (Lyrically.) The tears of the world are a constant quantity. For each one who begins to weep, somewhere else another stops. The same is true of the laugh. (He laughs.) Let us not then speak ill of our generation, it is not any unhappier than its predecessors. (Pause.) Let us not speak well of it either. (Pause.) Let us not speak of it at all. (Pause. Judiciously.) It is true the population has increased.\n"
"VLADIMIR:\n"
"Try and walk.\n"
"Estragon takes a few limping steps, stops before Lucky and spits on him, then goes and sits down on the mound.\n"
"POZZO:\n"
"Guess who taught me all these beautiful things. (Pause. Pointing to Lucky.) My Lucky!\n"
"VLADIMIR:\n"
"(looking at the sky.) Will night never come?\n"
"POZZO:\n"
"But for him all my thoughts, all my feelings, would have been of common things. (Pause. With extraordinary vehemence.) Professional worries! (Calmer.) Beauty, grace, truth of the first water, I knew they were all beyond me. So I took a knook. VLADIMIR:\n"
"(startled from his inspection of the sky). A knook?\n"
"POZZO:\n"
"That was nearly sixty years ago ... (he consults his watch) ... yes, nearly sixty. (Drawing himself up proudly.) You wouldn't think it to look at me, would you? Compared to him I look like a young man, no? (Pause.) Hat! (Lucky puts down the basket and takes off his hat. His long white hair falls about his face. He puts his hat under his arm and picks up the basket.) Now look. (Pozzo takes off his hat. [All four wear bowlers.] He is completely bald. He puts on his hat again.) Did you see?\n"
"VLADIMIR:\n"
"And now you turn him away? Such an old and faithful servant!\n"
"ESTRAGON:\n"
"Swine!\n"
"Pozzo more and more agitated.\n"
"\n"
"VLADIMIR:\n"
"After having sucked all the good out of him you chuck him away like a ... like a banana skin. Really ...\n"
"POZZO:\n"
"(groaning, clutching his head). I can't bear it ... any longer ... the way he goes on ... you've no idea ... it's terrible ... he must go ... (he waves his arms) ... I'm going mad ... (he collapses, his head in his hands) ... I can't bear it ... any longer ...\n"
"Silence. All look at Pozzo.\n"
"VLADIMIR:\n"
"He can't bear it.\n"
"ESTRAGON:\n"
"Any longer.\n"
"VLADIMIR:\n"
"He's going mad.\n"
"ESTRAGON:\n"
"It's terrible.\n"
"VLADIMIR:\n"
"(to Lucky). How dare you! It's abominable! Such a good master! Crucify him like that! After so many years! Really!\n"
"POZZO:\n"
"(sobbing). He used to be so kind ... so helpful ... and entertaining ... my good angel ... and now ... he's killing me.\n"
"ESTRAGON:\n"
"( to Vladimir). Does he want to replace him? VLADIMIR:\n"
"What?\n"
"ESTRAGON:\n"
"Does he want someone to take his place or not?\n"
"VLADIMIR:\n"
"I don't think so.\n"
"ESTRAGON:\n"
"What?\n"
"VLADIMIR:\n"
"I don't know.\n"
"ESTRAGON:\n"
"Ask him.\n"
"POZZO:\n"
"(calmer). Gentlemen, I don't know what came over me. Forgive me. Forget all I said. (More and more his old self.) I don't remember exactly what it was, but you may be sure there wasn't a word of truth in it. (Drawing himself up, striking his chest.) Do I look like a man that can be made to suffer? Frankly? (He rummages in his pockets.) What have I done with my pipe?\n"
"VLADIMIR:\n"
"Charming evening we're having.\n"
"ESTRAGON:\n"
"\n"
"Unforgettable.\n"
"VLADIMIR:\n"
"And it's not over.\n"
"ESTRAGON:\n"
"Apparently not.\n"
"VLADIMIR:\n"
"It's only beginning.\n"
"ESTRAGON:\n"
"It's awful.\n"
"VLADIMIR:\n"
"Worse than the pantomime.\n"
"ESTRAGON:\n"
"The circus.\n"
"VLADIMIR:\n"
"The music-hall.\n"
"ESTRAGON:\n"
"The circus.\n"
"POZZO:\n"
"What can I have done with that briar?\n"
"ESTRAGON:\n"
"He's a scream. He's lost his dudeen.\n"
"Laughs noisily.\n"
"VLADIMIR:\n"
"I'll be back.\n"
"He hastens towards the wings.\n"
"ESTRAGON:\n"
"End of the corridor, on the left.\n"
"VLADIMIR:\n"
"Keep my seat.\n"
"Exit Vladimir.\n"
"POZZO:\n"
"(on the point of tears). I've lost my Kapp and Peterson! ESTRAGON:\n"
"(convulsed with merriment). He'll be the death of me! POZZO:\n"
"You didn't see by any chance– (He misses Vladimir.) Oh! He's gone! Without saying goodbye! How could he! He might have waited!\n"
"ESTRAGON:\n"
"He would have burst.\n"
"POZZO:\n"
"Oh! (Pause.) Oh well then of course in that case ... ESTRAGON:\n"
"Come here.\n"
"POZZO:\n"
"What for?\n"
"ESTRAGON:\n"
"\n"
"You'll see.\n"
"POZZO:\n"
"You want me to get up?\n"
"ESTRAGON:\n"
"Quick! (Pozzo gets up and goes over beside Estragon. Estragon points off.) Look! POZZO:\n"
"(having put on his glasses). Oh I say!\n"
"ESTRAGON:\n"
"It's all over.\n"
"Enter Vladimir, somber. He shoulders Lucky out of his way, kicks over the stool, comes and goes agitatedly.\n"
"POZZO:\n"
"He's not pleased.\n"
"ESTRAGON:\n"
"(to Vladimir). You missed a treat. Pity.\n"
"Vladimir halts, straightens the stool, comes and goes, calmer.\n"
"POZZO:\n"
"He subsides. (Looking round.) Indeed all subsides. A great calm descends. (Raising his hand.) Listen! Pan sleeps.\n"
"VLADIMIR:\n"
"Will night never come?\n"
"All three look at the sky.\n"
"POZZO:\n"
"You don't feel like going until it does?\n"
"ESTRAGON:\n"
"Well you see—\n"
"POZZO:\n"
"Why it's very natural, very natural. I myself in your situation, if I had an appointment with a Godin ... Godet ... Godot ... anyhow, you see who I mean, I'd wait till it was black night before I gave up. (He looks at the stool.) I'd very much like to sit down, but I don't quite know how to go about it.\n"
"ESTRAGON:\n"
"Could I be of any help?\n"
"POZZO:\n"
"If you asked me perhaps.\n"
"ESTRAGON:\n"
"What?\n"
"POZZO:\n"
"If you asked me to sit down.\n"
"ESTRAGON:\n"
"Would that be a help?\n"
"POZZO:\n"
"I fancy so.\n"
"ESTRAGON:\n"
"Here we go. Be seated, Sir, I beg of you.\n"
"POZZO:\n"
"\n"
"No no, I wouldn't think of it! (Pause. Aside.) Ask me again. ESTRAGON:\n"
"Come come, take a seat I beseech you, you'll get pneumonia. POZZO:\n"
"You really think so?\n"
"ESTRAGON:\n"
"Why it's absolutely certain.\n"
"POZZO:\n"
"No doubt you are right. (He sits down.) Done it again! (Pause.) Thank you, dear fellow. (He consults his watch.) But I must really be getting along, if I am to observe my schedule.\n"
"VLADIMIR:\n"
"Time has stopped.\n"
"POZZO:\n"
"(cuddling his watch to his ear). Don't you believe it, Sir, don't you believe it. (He puts his watch back in his pocket.) Whatever you like, but not that. ESTRAGON:\n"
"(to Pozzo). Everything seems black to him today.\n"
"POZZO:\n"
"Except the firmament. (He laughs, pleased with this witticism.) But I see what it is, you are not from these parts, you don't know what our twilights can do. Shall I tell you? (Silence. Estragon is fiddling with his boot again, Vladimir with his hat.) I can't refuse you. (Vaporizer.) A little attention, if you please. (Vladimir and Estragon continue their fiddling, Lucky is half asleep. Pozzo cracks his whip feebly.) What's the matter with this whip? (He gets up and cracks it more vigorously, finally with success. Lucky jumps. Vladimir's hat, Estragon's boot, Lucky's hat, fall to the ground. Pozzo throws down the whip.) Worn out, this whip. (He looks at Vladimir and Estragon.) What was I saying?\n"
"VLADIMIR:\n"
"Let's go.\n"
"ESTRAGON:\n"
"But take the weight off your feet, I implore you, you'll catch your death. POZZO:\n"
"True. (He sits down. To Estragon.) What is your name?\n"
"ESTRAGON:\n"
"Adam.\n"
"POZZO:\n"
"(who hasn't listened). Ah yes! The night. (He raises his head.) But be a little more attentive, for pity's sake, otherwise we'll never get anywhere. (He looks at the sky.) Look! (All look at the sky except Lucky who is dozing off again. Pozzo jerks the rope.) Will you look at the sky, pig! (Lucky looks at the sky.) Good, that's enough. (They stop looking at the sky.) What is there so extraordinary about it? Qua sky. It is pale and luminous like any sky at this hour of the day. (Pause.) In these latitudes. (Pause.) When the weather is fine. (Lyrical.) An hour ago (he looks at his watch, prosaic) roughly (lyrical) after having poured forth even since (he hesitates, prosaic) say ten o'clock in the morning (lyrical) tirelessly torrents of\n"
"\n"
"red and white light it begins to lose its effulgence, to grow pale (gesture of the two hands lapsing by stages) pale, ever a little paler, a little paler until (dramatic pause, ample gesture of the two hands flung wide apart) pppfff! finished! it comes to rest. But– (hand raised in admonition)– but behind this veil of gentleness and peace, night is charging (vibrantly) and will burst upon us (snaps his fingers) pop! like that! (his inspiration leaves him) just when we least expect it. (Silence. Gloomily.) That's how it is on this bitch of an earth.\n"
"Long silence.\n"
"ESTRAGON:\n"
"So long as one knows.\n"
"VLADIMIR:\n"
"One can bide one's time.\n"
"ESTRAGON:\n"
"One knows what to expect.\n"
"VLADIMIR:\n"
"No further need to worry.\n"
"ESTRAGON:\n"
"Simply wait.\n"
"VLADIMIR:\n"
"We're used to it.\n"
"He picks up his hat, peers inside it, shakes it, puts it on.\n"
"POZZO:\n"
"How did you find me? (Vladimir and Estragon look at him blankly.) Good? Fair? Middling? Poor? Positively bad?\n"
"VLADIMIR:\n"
"(first to understand). Oh very good, very very good.\n"
"POZZO:\n"
"(to Estragon). And you, Sir?\n"
"ESTRAGON:\n"
"Oh tray bong, tray tray tray bong.\n"
"POZZO:\n"
"(fervently). Bless you, gentlemen, bless you! (Pause.) I have such need of encouragement! (Pause.) I weakened a little towards the end, you didn't notice? VLADIMIR:\n"
"Oh perhaps just a teeny weeny little bit.\n"
"ESTRAGON:\n"
"I thought it was intentional.\n"
"POZZO:\n"
"You see my memory is defective.\n"
"Silence.\n"
"ESTRAGON:\n"
"In the meantime, nothing happens.\n"
"POZZO:\n"
"You find it tedious?\n"
"ESTRAGON:\n"
"Somewhat.\n"
"\n"
"POZZO:\n"
"(to Vladimir). And you, Sir? VLADIMIR:\n"
"I've been better entertained. Silence. Pozzo struggles inwardly. POZZO:\n"
"Gentlemen, you have been ... civil to me.\n"
"ESTRAGON:\n"
"Not at all!\n"
"VLADIMIR:\n"
"What an idea!\n"
"POZZO:\n"
"Yes yes, you have been correct. So that I ask myself is there anything I can do in my turn for these honest fellows who are having such a dull, dull time. ESTRAGON:\n"
"Even ten francs would be a help.\n"
"VLADIMIR:\n"
"We are not beggars!\n"
"POZZO:\n"
"Is there anything I can do, that's what I ask myself, to cheer them up? I have given them bones, I have talked to them about this and that, I have explained the twilight, admittedly. But is it enough, that's what tortures me, is it enough? ESTRAGON:\n"
"Even five.\n"
"VLADIMIR:\n"
"(to Estragon, indignantly). That's enough! ESTRAGON:\n"
"I couldn't accept less.\n"
"POZZO:\n"
"Is is enough? No doubt. But I am liberal. It's my nature. This evening. So much the worse for me. (He jerks the rope. Lucky looks at him.) For I shall suffer, no doubt about that. (He picks up the whip.) What do you prefer? Shall we have him dance, or sing, or recite, or think, or—\n"
"ESTRAGON:\n"
"Who?\n"
"POZZO:\n"
"Who! You know how to think, you two?\n"
"VLADIMIR:\n"
"He thinks?\n"
"POZZO:\n"
"Certainly. Aloud. He even used to think very prettily once, I could listen to him for hours. Now ... (he shudders). So much the worse for me. Well, would you like him to think something for us?\n"
"ESTRAGON:\n"
"I'd rather he dance, it'd be more fun.\n"
"POZZO:\n"
"\n"
"Not necessarily.\n"
"ESTRAGON:\n"
"Wouldn't it, Didi, be more fun?\n"
"VLADIMIR:\n"
"I'd like well to hear him think.\n"
"ESTRAGON:\n"
"Perhaps he could dance first and think afterwards, if it isn't too much to ask him.\n"
"VLADIMIR:\n"
"(to Pozzo). Would that be possible?\n"
"POZZO:\n"
"By all means, nothing simpler. It's the natural order.\n"
"He laughs briefly.\n"
"VLADIMIR:\n"
"Then let him dance.\n"
"Silence.\n"
"POZZO:\n"
"Do you hear, hog?\n"
"ESTRAGON:\n"
"He never refuses?\n"
"POZZO:\n"
"He refused once. (Silence.) Dance, misery!\n"
"Lucky puts down bag and basket, advances towards front, turns to Pozzo. Lucky dances. He stops.\n"
"ESTRAGON:\n"
"Is that all?\n"
"POZZO:\n"
"Encore!\n"
"Lucky executes the same movements, stops.\n"
"ESTRAGON:\n"
"Pooh! I'd do as well myself. (He imitates Lucky, almost falls.) With a little practice.\n"
"POZZO:\n"
"He used to dance the farandole, the fling, the brawl, the jig, the fandango and even the hornpipe. He capered. For joy. Now that's the best he can do. Do you know what he calls it?\n"
"ESTRAGON:\n"
"The Scapegoat's Agony.\n"
"VLADIMIR:\n"
"The Hard Stool.\n"
"POZZO:\n"
"The Net. He thinks he's entangled in a net.\n"
"VLADIMIR:\n"
"(squirming like an aesthete). There's something about it ...\n"
"Lucky makes to return to his burdens.\n"
"POZZO:\n"
"Woaa!\n"
"\n"
"Lucky stiffens.\n"
"ESTRAGON:\n"
"Tell us about the time he refused.\n"
"POZZO:\n"
"With pleasure, with pleasure. (He fumbles in his pockets.) Wait. (He fumbles.) What have I done with my spray? (He fumbles.) Well now isn't that ... (He looks up, consternation on his features. Faintly.) I can't find my pulverizer! ESTRAGON:\n"
"(faintly). My left lung is very weak! (He coughs feebly. In ringing tones.) But my right lung is as sound as a bell!\n"
"POZZO:\n"
"(normal voice). No matter! What was I saying. (He ponders.) Wait. (Ponders.) Well now isn't that ... (He raises his head.) Help me!\n"
"ESTRAGON:\n"
"Wait!\n"
"VLADIMIR:\n"
"Wait!\n"
"POZZO:\n"
"Wait!\n"
"All three take off their hats simultaneously, press their hands to their foreheads, concentrate.\n"
"ESTRAGON:\n"
"(triumphantly). Ah!\n"
"VLADIMIR:\n"
"He has it.\n"
"POZZO:\n"
"(impatient). Well?\n"
"ESTRAGON:\n"
"Why doesn't he put down his bags?\n"
"VLADIMIR:\n"
"Rubbish!\n"
"POZZO:\n"
"Are you sure?\n"
"VLADIMIR:\n"
"Damn it haven't you already told us?\n"
"POZZO:\n"
"I've already told you?\n"
"ESTRAGON:\n"
"He's already told us?\n"
"VLADIMIR:\n"
"Anyway he has put them down.\n"
"ESTRAGON:\n"
"(glance at Lucky). So he has. And what of it?\n"
"VLADIMIR:\n"
"Since he has put down his bags it is impossible we should have asked why he does not do so.\n"
"\n"
"POZZO:\n"
"Stoutly reasoned!\n"
"ESTRAGON:\n"
"And why has he put them down?\n"
"POZZO:\n"
"Answer us that.\n"
"VLADIMIR:\n"
"In order to dance.\n"
"ESTRAGON:\n"
"True!\n"
"POZZO:\n"
"True!\n"
"Silence. They put on their hats.\n"
"ESTRAGON:\n"
"Nothing happens, nobody comes, nobody goes, it's awful!\n"
"VLADIMIR:\n"
"(to Pozzo). Tell him to think. POZZO:\n"
"Give him his hat. VLADIMIR:\n"
"His hat?\n"
"POZZO:\n"
"He can't think without his hat.\n"
"VLADIMIR:\n"
"(to Estragon). Give him his hat.\n"
"ESTRAGON:\n"
"Me! After what he did to me! Never!\n"
"VLADIMIR:\n"
"I'll give it to him.\n"
"He does not move.\n"
"ESTRAGON:\n"
"(to Pozzo). Tell him to go and fetch it.\n"
"POZZO:\n"
"It's better to give it to him.\n"
"VLADIMIR:\n"
"I'll give it to him.\n"
"He picks up the hat and tenders it at arm's length to Lucky, who does not move. POZZO:\n"
"You must put it on his head.\n"
"ESTRAGON:\n"
"(to Pozzo). Tell him to take it.\n"
"POZZO:\n"
"It's better to put it on his head.\n"
"VLADIMIR:\n"
"I'll put it on his head.\n"
"\n"
"He goes round behind Lucky, approaches him cautiously, puts the hat on his head and recoils smartly. Lucky does not move. Silence.\n"
"ESTRAGON:\n"
"What's he waiting for?\n"
"POZZO:\n"
"Stand back! (Vladimir and Estragon move away from Lucky. Pozzo jerks the rope. Lucky looks at Pozzo.) Think, pig! (Pause. Lucky begins to dance.) Stop! (Lucky stops.) Forward! (Lucky advances.) Stop! (Lucky stops.) Think!\n"
"Silence.\n"
"LUCKY:\n"
"On the other hand with regard to—\n"
"POZZO:\n"
"Stop! (Lucky stops.) Back! (Lucky moves back.) Stop! (Lucky stops.) Turn! (Lucky turns towards auditorium.) Think!\n"
"During Lucky's tirade the others react as follows.\n"
"1) Vladimir and Estragon all attention, Pozzo dejected and disgusted.\n"
"2) Vladimir and Estragon begin to protest, Pozzo's sufferings increase.\n"
"3) Vladimir and Estragon attentive again, Pozzo more and more agitated and groaning.\n"
"4) Vladimir and Estragon protest violently. Pozzo jumps up, pulls on the rope. General outcry. Lucky pulls on the rope, staggers, shouts his text. All three throw themselves on Lucky who struggles and shouts his text.\n"
"LUCKY:\n"
"Given the existence as uttered forth in the public works of Puncher and Wattmann of a personal God quaquaquaqua with white beard quaquaquaqua outside time without extension who from the heights of divine apathia divine athambia divine aphasia loves us dearly with some exceptions for reasons unknown but time will tell and suffers like the divine Miranda with those who for reasons unknown but time will tell are plunged in torment plunged in fire whose fire flames if that continues and who can doubt it will fire the firmament that is to say blast hell to heaven so blue still and calm so calm with a calm which even though intermittent is better than nothing but not so fast and considering what is more that as a result of the labors left unfinished crowned by the Acacacacademy of Anthropopopometry of Essy-in-Possy of Testew and Cunard it is established beyond all doubt all other doubt than that which clings to the labors of men that as a result of the labors unfinished of Testew and Cunnard it is established as hereinafter but not so fast for reasons unknown that as a result of the public works of Puncher and Wattmann it is established beyond all doubt that in view of the labors of Fartov and Belcher left unfinished for reasons unknown of Testew and Cunard left unfinished it is established what many deny that man in Possy of Testew and Cunard that man in Essy that man in short that man in brief in spite of the strides of alimentation and defecation wastes and pines wastes and pines and concurrently simultaneously what is more for reasons unknown\n"
"\n"
"in spite of the strides of physical culture the practice of sports such as tennis football running cycling swimming flying floating riding gliding conating camogie skating tennis of all kinds dying flying sports of all sorts autumn summer winter winter tennis of all kinds hockey of all sorts penicillin and succedanea in a word I resume flying gliding golf over nine and eighteen holes tennis of all sorts in a word for reasons unknown in Feckham Peckham Fulham Clapham namely concurrently simultaneously what is more for reasons unknown but time will tell fades away I resume Fulham Clapham in a word the dead loss per head since the death of Bishop Berkeley being to the tune of one inch four ounce per head approximately by and large more or less to the nearest decimal good measure round figures stark naked in the stockinged feet in Connemara in a word for reasons unknown no matter what matter the facts are there and considering what is more much more grave that in the light of the labors lost of Steinweg and Peterman it appears what is more much more grave that in the light the light the light of the labors lost of Steinweg and Peterman that in the plains in the mountains by the seas by the rivers running water running fire the air is the same and then the earth namely the air and then the earth in the great cold the great dark the air and the earth abode of stones in the great cold alas alas in the year of their Lord six hundred and something the air the earth the sea the earth abode of stones in the great deeps the great cold on sea on land and in the air I resume for reasons unknown in spite of the tennis the facts are there but time will tell I resume alas alas on on in short in fine on on abode of stones who can doubt it I resume but not so fast I resume the skull fading fading fading and concurrently simultaneously what is more for reasons unknown in spite of the tennis on on the beard the flames the tears the stones so blue so calm alas alas on on the skull the skull the skull the skull in Connemara in spite of the tennis the labors abandoned left unfinished graver still abode of stones in a word I resume alas alas abandoned unfinished the skull the skull in Connemara in spite of the tennis the skull alas the stones Cunard (mêlée, final vociferations)\n"
"... tennis ... the stones ... so calm ... Cunard ... unfinished ...\n"
"POZZO:\n"
"His hat!\n"
"Vladimir seizes Lucky's hat. Silence of Lucky. He falls. Silence. Panting of the victors.\n"
"ESTRAGON:\n"
"Avenged!\n"
"Vladimir examines the hat, peers inside it.\n"
"POZZO:\n"
"Give me that! (He snatches the hat from Vladimir, throws it on the ground, tramples on it.) There's an end to his thinking!\n"
"VLADIMIR:\n"
"But will he be able to walk?\n"
"POZZO:\n"
"\n"
"Walk or crawl! (He kicks Lucky.) Up pig! ESTRAGON:\n"
"Perhaps he's dead.\n"
"VLADIMIR:\n"
"You'll kill him.\n"
"POZZO:\n"
"Up scum! (He jerks the rope.) Help me! VLADIMIR:\n"
"How?\n"
"POZZO:\n"
"Raise him up!\n"
"Vladimir and Estragon hoist Lucky to his feet, support him an instant, then let him go. He falls.\n"
"ESTRAGON:\n"
"He's doing it on purpose!\n"
"POZZO:\n"
"You must hold him. (Pause.) Come on, come on, raise him up. ESTRAGON:\n"
"To hell with him!\n"
"VLADIMIR:\n"
"Come on, once more.\n"
"ESTRAGON:\n"
"What does he take us for?\n"
"They raise Lucky, hold him up.\n"
"POZZO:\n"
"Don't let him go! (Vladimir and Estragon totter.) Don't move! (Pozzo fetches bag and basket and brings them towards Lucky.) Hold him tight! (He puts the bag in Lucky's hand. Lucky drops it immediately.) Don't let him go! (He puts back the bag in Lucky's hand. Gradually, at the feel of the bag, Lucky recovers his senses and his fingers finally close round the handle.) Hold him tight! (As before with basket.) \n"
"Now! You can let him go. (Vladimir and Estragon move away from Lucky who totters, reels, sags, but succeeds in remaining on his feet, bag and basket in his hands. Pozzo steps back, cracks his whip.) Forward! (Lucky totters forward.) Back! (Lucky totters back.) Turn! (Lucky turns.) Done it! He can walk. (Turning to Vladimir and Estragon.) Thank you, gentlemen, and let me ... (he fumbles in his pockets) ... let me wish you ... (fumbles) ... wish you ... (fumbles) ... what have I done with my watch? (Fumbles.) A genuine half-hunter, gentlemen, with deadbeat escapement! (Sobbing.) Twas my granpa gave it to me! (He searches on the ground, Vladimir and Estragon likewise. Pozzo turns over with his foot the remains of Lucky's hat.) Well now isn't that just—\n"
"VLADIMIR:\n"
"Perhaps it's in your fob.\n"
"POZZO:\n"
"\n"
"Wait! (He doubles up in an attempt to apply his ear to his stomach, listens. Silence.) I hear nothing. (He beckons them to approach, Vladimir and Estragon go over to him, bend over his stomach.) Surely one should hear the tick-tick. VLADIMIR:\n"
"Silence!\n"
"All listen, bent double. \n"
"ESTRAGON:\n"
"I hear something.\n"
"POZZO:\n"
"Where?\n"
"VLADIMIR:\n"
"It's the heart.\n"
"POZZO:\n"
"(disappointed). Damnation!\n"
"VLADIMIR:\n"
"Silence!\n"
"ESTRAGON:\n"
"Perhaps it has stopped.\n"
"They straighten up.\n"
"POZZO:\n"
"Which of you smells so bad?\n"
"ESTRAGON:\n"
"He has stinking breath and I have stinking feet.\n"
"POZZO:\n"
"I must go.\n"
"ESTRAGON:\n"
"And your half-hunter?\n"
"POZZO:\n"
"I must have left it at the manor.\n"
"Silence.\n"
"ESTRAGON:\n"
"Then adieu.\n"
"POZZO:\n"
"Adieu.\n"
"VLADIMIR:\n"
"Adieu.\n"
"POZZO:\n"
"Adieu.\n"
"Silence. No one moves.\n"
"VLADIMIR:\n"
"Adieu.\n"
"POZZO:\n"
"Adieu.\n"
"ESTRAGON:\n"
"Adieu.\n"
"Silence.\n"
"\n"
"POZZO:\n"
"And thank you.\n"
"VLADIMIR:\n"
"Thank you. POZZO:\n"
"Not at all. ESTRAGON: Yes yes. POZZO:\n"
"No no.\n"
"VLADIMIR:\n"
"Yes yes.\n"
"ESTRAGON:\n"
"No no.\n"
"Silence.\n"
"POZZO:\n"
"I don't seem to be able ... (long hesitation) ... to depart.\n"
"ESTRAGON:\n"
"Such is life.\n"
"Pozzo turns, moves away from Lucky towards the wings, paying out the rope as he goes.\n"
"VLADIMIR:\n"
"You're going the wrong way.\n"
"POZZO:\n"
"I need a running start. (Having come to the end of the rope, i.e., off stage, he stops, turns and cries.) Stand back! (Vladimir and Estragon stand back, look towards Pozzo. Crack of whip.) On! On!\n"
"ESTRAGON:\n"
"On!\n"
"VLADIMIR:\n"
"On!\n"
"Lucky moves off.\n"
"POZZO:\n"
"Faster! (He appears, crosses the stage preceded by Lucky. Vladimir and Estragon wave their hats. Exit Lucky.) On! On! (On the point of disappearing in his turn he stops and turns. The rope tautens. Noise of Lucky falling off.) Stool! (Vladimir fetches stool and gives it to Pozzo who throws it to Lucky.) Adieu!\n"
"VLADIMIR and ESTRAGON:\n"
"(waving). Adieu! Adieu!\n"
"POZZO:\n"
"Up! Pig! (Noise of Lucky getting up.) On! (Exit Pozzo.) Faster! On! Adieu! Pig! Yip! Adieu!\n"
"Long silence.\n"
"VLADIMIR:\n"
"That passed the time.\n"
"ESTRAGON:\n"
"\n"
"It would have passed in any case.\n"
"VLADIMIR:\n"
"Yes, but not so rapidly.\n"
"Pause.\n"
"ESTRAGON:\n"
"What do we do now?\n"
"VLADIMIR:\n"
"I don't know.\n"
"ESTRAGON:\n"
"Let's go.\n"
"VLADIMIR:\n"
"We can't.\n"
"ESTRAGON:\n"
"Why not?\n"
"VLADIMIR:\n"
"We're waiting for Godot.\n"
"ESTRAGON:\n"
"(despairingly). Ah! Pause.\n"
"VLADIMIR:\n"
"How they've changed! ESTRAGON:\n"
"Who?\n"
"VLADIMIR:\n"
"Those two.\n"
"ESTRAGON:\n"
"That's the idea, let's make a little conversation.\n"
"VLADIMIR:\n"
"Haven't they?\n"
"ESTRAGON:\n"
"What?\n"
"VLADIMIR:\n"
"Changed.\n"
"ESTRAGON:\n"
"Very likely. They all change. Only we can't.\n"
"VLADIMIR:\n"
"Likely! It's certain. Didn't you see them?\n"
"ESTRAGON:\n"
"I suppose I did. But I don't know them.\n"
"VLADIMIR:\n"
"Yes you do know them.\n"
"ESTRAGON:\n"
"No I don't know them.\n"
"VLADIMIR:\n"
"We know them, I tell you. You forget everything. (Pause. To himself.) Unless they're not the same ...\n"
"\n"
"ESTRAGON:\n"
"Why didn't they recognize us then?\n"
"VLADIMIR:\n"
"That means nothing. I too pretended not to recognize them. And then nobody ever recognizes us.\n"
"ESTRAGON:\n"
"Forget it. What we need– Ow! (Vladimir does not react.) Ow!\n"
"VLADIMIR:\n"
"(to himself). Unless they're not the same ... ESTRAGON:\n"
"Didi! It's the other foot!\n"
"He goes hobbling towards the mound. VLADIMIR:\n"
"Unless they're not the same ...\n"
"BOY:\n"
"(off). Mister!\n"
"Estragon halts. Both look towards the voice.\n"
"ESTRAGON:\n"
"Off we go again.\n"
"VLADIMIR:\n"
"Approach, my child.\n"
"Enter Boy, timidly. He halts.\n"
"BOY:\n"
"Mister Albert ... ?\n"
"VLADIMIR:\n"
"Yes.\n"
"ESTRAGON:\n"
"What do you want?\n"
"VLADIMIR:\n"
"Approach!\n"
"The Boy does not move.\n"
"ESTRAGON:\n"
"(forcibly). Approach when you're told, can't you?\n"
"The Boy advances timidly, halts.\n"
"VLADIMIR:\n"
"What is it?\n"
"BOY:\n"
"Mr. Godot ...\n"
"VLADIMIR:\n"
"Obviously ... (Pause.) Approach.\n"
"ESTRAGON:\n"
"(violently). Will you approach! (The Boy advances timidly.) What kept you so late?\n"
"VLADIMIR:\n"
"You have a message from Mr. Godot?\n"
"BOY:\n"
"\n"
"Yes Sir.\n"
"VLADIMIR:\n"
"Well, what is it?\n"
"ESTRAGON:\n"
"What kept you so late?\n"
"The Boy looks at them in turn, not knowing to which he should reply.\n"
"VLADIMIR:\n"
"(to Estragon). Let him alone.\n"
"ESTRAGON:\n"
"(violently). You let me alone. (Advancing, to the Boy.) Do you know what time it is?\n"
"BOY:\n"
"(recoiling). It's not my fault, Sir.\n"
"ESTRAGON:\n"
"And whose is it? Mine?\n"
"BOY:\n"
"I was afraid, Sir.\n"
"ESTRAGON:\n"
"Afraid of what? Of us? (Pause.) Answer me!\n"
"VLADIMIR:\n"
"I know what it is, he was afraid of the others.\n"
"ESTRAGON:\n"
"How long have you been here?\n"
"BOY:\n"
"A good while, Sir.\n"
"VLADIMIR:\n"
"You were afraid of the whip?\n"
"BOY:\n"
"Yes Sir.\n"
"VLADIMIR:\n"
"The roars?\n"
"BOY:\n"
"Yes Sir.\n"
"VLADIMIR:\n"
"The two big men.\n"
"BOY:\n"
"Yes Sir.\n"
"VLADIMIR:\n"
"Do you know them?\n"
"BOY:\n"
"No Sir.\n"
"VLADIMIR:\n"
"Are you a native of these parts? (Silence.) Do you belong to these parts?\n"
"BOY:\n"
"Yes Sir.\n"
"ESTRAGON:\n"
"\n"
"That's all a pack of lies. (Shaking the Boy by the arm.) Tell us the truth! BOY:\n"
"(trembling). But it is the truth, Sir!\n"
"VLADIMIR:\n"
"Will you let him alone! What's the matter with you? \n"
"(Estragon releases the Boy, moves away, covering his face with his hands. Vladimir and the Boy observe him. Estragon drops his hands. His face is convulsed.) What's the matter with you?\n"
"ESTRAGON:\n"
"I'm unhappy.\n"
"VLADIMIR:\n"
"Not really! Since when?\n"
"ESTRAGON:\n"
"I'd forgotten.\n"
"VLADIMIR:\n"
"Extraordinary the tricks that memory plays! (Estragon tries to speak, renounces, limps to his place, sits down and begins to take off his boots. To Boy.) Well? BOY:\n"
"Mr. Godot—\n"
"VLADIMIR:\n"
"I've seen you before, haven't I?\n"
"BOY:\n"
"I don't know, Sir.\n"
"VLADIMIR:\n"
"You don't know me?\n"
"BOY:\n"
"No Sir.\n"
"VLADIMIR:\n"
"It wasn't you came yesterday?\n"
"BOY:\n"
"No Sir.\n"
"VLADIMIR:\n"
"This is your first time?\n"
"BOY:\n"
"Yes Sir.\n"
"Silence.\n"
"VLADIMIR:\n"
"Words words. (Pause.) Speak.\n"
"BOY:\n"
"(in a rush). Mr. Godot told me to tell you he won't come this evening but surely tomorrow.\n"
"Silence.\n"
"VLADIMIR:\n"
"Is that all?\n"
"BOY:\n"
"Yes Sir.\n"
"\n"
"Silence.\n"
"VLADIMIR:\n"
"You work for Mr. Godot?\n"
"BOY:\n"
"Yes Sir.\n"
"VLADIMIR:\n"
"What do you do?\n"
"BOY:\n"
"I mind the goats, Sir.\n"
"VLADIMIR:\n"
"Is he good to you?\n"
"BOY:\n"
"Yes Sir.\n"
"VLADIMIR:\n"
"He doesn't beat you?\n"
"BOY:\n"
"No Sir, not me.\n"
"VLADIMIR:\n"
"Whom does he beat?\n"
"BOY:\n"
"He beats my brother, Sir.\n"
"VLADIMIR:\n"
"Ah, you have a brother?\n"
"BOY:\n"
"Yes Sir.\n"
"VLADIMIR:\n"
"What does he do?\n"
"BOY:\n"
"He minds the sheep, Sir.\n"
"VLADIMIR:\n"
"And why doesn't he beat you?\n"
"BOY:\n"
"I don't know, Sir.\n"
"VLADIMIR:\n"
"He must be fond of you.\n"
"BOY:\n"
"I don't know, Sir.\n"
"Silence.\n"
"VLADIMIR:\n"
"Does he give you enough to eat? (The Boy hesitates.) Does he feed you well? BOY:\n"
"Fairly well, Sir.\n"
"VLADIMIR:\n"
"You're not unhappy? (The Boy hesitates.) Do you hear me? BOY:\n"
"Yes Sir.\n"
"\n"
"VLADIMIR:\n"
"Well?\n"
"BOY:\n"
"I don't know, Sir.\n"
"VLADIMIR:\n"
"You don't know if you're unhappy or not?\n"
"BOY:\n"
"No Sir.\n"
"VLADIMIR:\n"
"You're as bad as myself. (Silence.) Where do you sleep? BOY:\n"
"In the loft, Sir.\n"
"VLADIMIR:\n"
"With your brother?\n"
"BOY:\n"
"Yes Sir.\n"
"VLADIMIR:\n"
"In the hay?\n"
"BOY:\n"
"Yes Sir.\n"
"Silence.\n"
"VLADIMIR:\n"
"All right, you may go.\n"
"BOY:\n"
"What am I to tell Mr. Godot, Sir?\n"
"VLADIMIR:\n"
"Tell him ... (he hesitates) ... tell him you saw us. (Pause.) You did see us, didn't you?\n"
"BOY:\n"
"Yes Sir.\n"
"He steps back, hesitates, turns and exit running. The light suddenly fails. In a moment it is night. The moon rises at back, mounts in the sky, stands still, shedding a pale light on the scene.\n"
"VLADIMIR:\n"
"At last! (Estragon gets up and goes towards Vladimir, a boot in each hand. He puts them down at edge of stage, straightens and contemplates the moon.) What are you doing?\n"
"ESTRAGON:\n"
"Pale for weariness.\n"
"VLADIMIR:\n"
"Eh?\n"
"ESTRAGON:\n"
"Of climbing heaven and gazing on the likes of us.\n"
"VLADIMIR:\n"
"Your boots, what are you doing with your boots?\n"
"ESTRAGON:\n"
"\n"
"(turning to look at the boots). I'm leaving them there. (Pause.) Another will come, just as ... as ... as me, but with smaller feet, and they'll make him happy. VLADIMIR:\n"
"But you can't go barefoot!\n"
"ESTRAGON:\n"
"Christ did.\n"
"VLADIMIR:\n"
"Christ! What has Christ got to do with it. You're not going to compare yourself to Christ!\n"
"ESTRAGON:\n"
"All my life I've compared myself to him.\n"
"VLADIMIR:\n"
"But where he lived it was warm, it was dry!\n"
"ESTRAGON:\n"
"Yes. And they crucified quick.\n"
"Silence.\n"
"VLADIMIR:\n"
"We've nothing more to do here.\n"
"ESTRAGON:\n"
"Nor anywhere else.\n"
"VLADIMIR:\n"
"Ah Gogo, don't go on like that. Tomorrow everything will be better.\n"
"ESTRAGON:\n"
"How do you make that out?\n"
"VLADIMIR:\n"
"Did you not hear what the child said?\n"
"ESTRAGON:\n"
"No.\n"
"VLADIMIR:\n"
"He said that Godot was sure to come tomorrow. (Pause.) What do you say to that? ESTRAGON:\n"
"Then all we have to do is to wait on here.\n"
"VLADIMIR:\n"
"Are you mad? We must take cover. (He takes Estragon by the arm.) Come on. He draws Estragon after him. Estragon yields, then resists. They halt. ESTRAGON:\n"
"(looking at the tree). Pity we haven't got a bit of rope.\n"
"VLADIMIR:\n"
"Come on. It's cold.\n"
"He draws Estragon after him. As before.\n"
"ESTRAGON:\n"
"Remind me to bring a bit of rope tomorrow.\n"
"VLADIMIR:\n"
"Yes. Come on.\n"
"He draws him after him. As before.\n"
"ESTRAGON:\n"
"\n"
"How long have we been together all the time now?\n"
"VLADIMIR:\n"
"I don't know. Fifty years maybe.\n"
"ESTRAGON:\n"
"Do you remember the day I threw myself into the Rhone?\n"
"VLADIMIR:\n"
"We were grape harvesting.\n"
"ESTRAGON:\n"
"You fished me out.\n"
"VLADIMIR:\n"
"That's all dead and buried.\n"
"ESTRAGON:\n"
"My clothes dried in the sun.\n"
"VLADIMIR:\n"
"There's no good harking back on that. Come on.\n"
"He draws him after him. As before.\n"
"ESTRAGON:\n"
"Wait!\n"
"VLADIMIR:\n"
"I'm cold!\n"
"ESTRAGON:\n"
"Wait! (He moves away from Vladimir.) I sometimes wonder if we wouldn't have been better off alone, each one for himself. (He crosses the stage and sits down on the mound.) We weren't made for the same road.\n"
"VLADIMIR:\n"
"(without anger). It's not certain.\n"
"ESTRAGON:\n"
"No, nothing is certain.\n"
"Vladimir slowly crosses the stage and sits down beside Estragon. VLADIMIR:\n"
"We can still part, if you think it would be better.\n"
"ESTRAGON:\n"
"It's not worthwhile now.\n"
"Silence.\n"
"VLADIMIR:\n"
"No, it's not worthwhile now.\n"
"Silence.\n"
"ESTRAGON:\n"
"Well, shall we go?\n"
"VLADIMIR:\n"
"Yes, let's go.\n"
"They do not move.\n"
"Curtain.\n";
volatile static const char* luckySpeech = godot1 + 50504;
static const int luckySpeechLength = 3927;
static const String luckySpeechTitle[3] = {"\"Lucky's", "Speech\"", "from WfG"};
