static const String bradburyTitle[] = {"Fahrenheit", "451 by", "Bradbury"};
static const int bradburyLength = 4013;
static const char bradbury[] PROGMEM =
"Granger unfolded an oilskin with some bacon in it. \"We'll have a bite. Then we'll turn around and walk upstream. They'll be needing us up that way.\"\n"
"Someone produced a small frying pan and the bacon went into it and the frying pan was set on the fire. After a moment the bacon began to flutter and dance in the pan and the sputter of it filled the morning air with its aroma. The men watched this ritual silently.\n"
"Granger looked into the fire.\n"
"\"Phoenix.\"\n"
"\"What?\"\n"
"\"There was a silly damn bird called a Phoenix back before Christ, every few hundred years he built a pyre and burned himself up. He must have been first cousin to Man. But every time he burnt himself up he sprang out of the ashes, he got himself born all over again. And it looks like we're doing the same thing, over and over, but we've got one damn thing the Phoenix never had. We know the damn silly thing we just did. We know all the damn silly things we've done for a thousand years and as long as we know that and always have it around where we can see it, some day we'll stop making the goddam funeral pyres and jumping in the middle of them. We pick up a few more people that remember, every generation.\"\n"
"He took the pan off the fire and let the bacon cool and they ate it, slowly, thoughtfully.\n"
"\"Now, let's get on upstream,\" said Granger. \"And hold onto one thought: You're not important. You're not anything. Some day the load we're carrying with us may help someone. But even when we had the books on hand, a long time ago, we didn't use what we got out of them. We went right on insulting the dead. We went right on spitting in the graves of all the poor ones who died before us. We're going to meet a lot of lonely people in the next week and the next month and the next year. And when they ask us what we're doing, you can say, We're remembering. That's where we'll win out in the long run. And some day we'll remember so much that we'll build the biggest goddam steamshovel in history and dig the biggest grave of all time and shove war in and cover it up. Come on now, we're going to go build a mirror factory first and put out nothing but mirrors for the next year and take a long look in them.\"\n"
"They finished eating and put out the fire. The day was brightening all about them as if a pink lamp had been given more wick. In the trees, the birds that had flown away quickly now came back and settled down.\n"
"Montag began walking and after a moment found that the others had fallen in behind him, going north. He was surprised, and moved aside to let Granger pass, but Granger looked at him and nodded him on. Montag went ahead. He looked at the river and the sky and the rusting track going back down to where the farms lay, where the barns stood full of hay, where a lot of people had walked by in the night on their way from the city. Later, in a month or six months, and certainly not more than a year, he would walk along here again, alone, and keep right on going until he caught up with the people.\n"
"But now there was a long morning's walk until noon, and if the men were silent it was because there was everything to think about and much to remember. Perhaps later in the morning, when the sun was up and had warmed them they would begin to talk, or just say the things they remembered, to be sure they were there, to be absolutely certain that things were safe in them. Montag felt the slow stir of words, the slow simmer. And when it came his turn, what could he say, what could he offer on a day like this, to make the trip a little easier? To everything there is a season. Yes. A time to break down, and a time to build up. Yes. A time to keep silence and a time to speak. Yes, all that. But what else. What else? Something, something....\n"
"And on either side of the river was there a tree of life, which bare twelve manner of fruits, and yielded her fruit every month; And the leaves of the tree were for the healing of the nations.\n"
"Yes, thought Montag, that's the one I'll save for noon. For noon....\n"
"When we reach the city.";
