static const String midsummerTitle[3] = {"A midsummer", "night's dream", "V.i.103-"};
static const int midsummerLength = 10485;
static const char midsummer[] PROGMEM = "Prologue\n"
"If we offend, it is with our good will./\n"
"That you should think, we come not to offend,/\n"
"But with good will. To show our simple skill,/\n"
"That is the true beginning of our end./\n"
"Consider then we come but in despite./\n"
"We do not come as minding to contest you,/\n"
"Our true intent is. All for your delight/\n"
"We are not here. That you should here repent you,/\n"
"The actors are at hand and by their show/\n"
"You shall know all that you are like to know.\n"
"THESEUS\n"
"This fellow doth not stand upon points.\n"
"LYSANDER\n"
"He hath rid his prologue like a rough colt; he knows/\n"
"not the stop. A good moral, my lord: it is not/\n"
"enough to speak, but to speak true.\n"
"HIPPOLYTA\n"
"Indeed he hath played on his prologue like a child/\n"
"on a recorder; a sound, but not in government./\n"
"THESEUS\n"
"His speech, was like a tangled chain; nothing/\n"
"impaired, but all disordered. Who is next?\n"
"[Enter Pyramus and Thisbe, Wall, Moonshine, and Lion]\n"
"\n"
"Prologue\n"
"Gentles, perchance you wonder at this show;/\n"
"But wonder on, till truth make all things plain./\n"
"This man is Pyramus, if you would know;/\n"
"This beauteous lady Thisby is certain./\n"
"This man, with lime and rough-cast, doth present/\n"
"Wall, that vile Wall which did these lovers sunder;/\n"
"And through Wall's chink, poor souls, they are content/\n"
"To whisper. At the which let no man wonder./\n"
"This man, with lanthorn, dog, and bush of thorn,/\n"
"Presenteth Moonshine; for, if you will know,/\n"
"By moonshine did these lovers think no scorn/\n"
"To meet at Ninus' tomb, there, there to woo./\n"
"This grisly beast, which Lion hight by name,/\n"
"The trusty Thisby, coming first by night,/\n"
"Did scare away, or rather did affright;/\n"
"And, as she fled, her mantle she did fall,/\n"
"Which Lion vile with bloody mouth did stain./\n"
"Anon comes Pyramus, sweet youth and tall,/\n"
"And finds his trusty Thisby's mantle slain:/\n"
"Whereat, with blade, with bloody blameful blade,/\n"
"He bravely broach'd is boiling bloody breast;/\n"
"And Thisby, tarrying in mulberry shade,/\n"
"His dagger drew, and died. For all the rest,/\n"
"Let Lion, Moonshine, Wall, and lovers twain/\n"
"At large discourse, while here they do remain.\n"
"[Exeunt Prologue, Thisbe, Lion, and Moonshine]\n"
"\n"
"THESEUS\n"
"I wonder if the lion be to speak.\n"
"DEMETRIUS\n"
"No wonder, my lord: one lion may, when many asses do.\n"
"Wall\n"
"In this same interlude it doth befall/\n"
"That I, one Snout by name, present a wall;/\n"
"And such a wall, as I would have you think,/\n"
"That had in it a crannied hole or chink,/\n"
"Through which the lovers, Pyramus and Thisby,/\n"
"Did whisper often very secretly./\n"
"This loam, this rough-cast and this stone doth show/\n"
"That I am that same wall; the truth is so:/\n"
"And this the cranny is, right and sinister,/\n"
"Through which the fearful lovers are to whisper.\n"
"THESEUS\n"
"Would you desire lime and hair to speak better?\n"
"DEMETRIUS\n"
"It is the wittiest partition that ever I heard/\n"
"discourse, my lord.\n"
"[Enter Pyramus]\n"
"\n"
"THESEUS\n"
"Pyramus draws near the wall: silence!\n"
"Pyramus\n"
"O grim-look'd night! O night with hue so black!/\n"
"O night, which ever art when day is not!/\n"
"O night, O night! alack, alack, alack,/\n"
"I fear my Thisby's promise is forgot!/\n"
"And thou, O wall, O sweet, O lovely wall,/\n"
"That stand'st between her father's ground and mine!/\n"
"Thou wall, O wall, O sweet and lovely wall,/\n"
"Show me thy chink, to blink through with mine eyne!\n"
"[Wall holds up his fingers]\n"
"\n"
"Thanks, courteous wall: Jove shield thee well for this!/\n"
"But what see I? No Thisby do I see./\n"
"O wicked wall, through whom I see no bliss!/\n"
"Cursed be thy stones for thus deceiving me!\n"
"THESEUS\n"
"The wall, methinks, being sensible, should curse again.\n"
"Pyramus\n"
"No, in truth, sir, he should not. 'Deceiving me'/\n"
"is Thisby's cue: she is to enter now, and I am to/\n"
"spy her through the wall. You shall see, it will/\n"
"fall pat as I told you. Yonder she comes.\n"
"[Enter Thisbe]\n"
"\n"
"Thisbe\n"
"O wall, full often hast thou heard my moans,/\n"
"For parting my fair Pyramus and me!/\n"
"My cherry lips have often kiss'd thy stones,/\n"
"Thy stones with lime and hair knit up in thee.\n"
"Pyramus\n"
"I see a voice: now will I to the chink,/\n"
"To spy an I can hear my Thisby's face. Thisby!\n"
"Thisbe\n"
"My love thou art, my love I think.\n"
"Pyramus\n"
"Think what thou wilt, I am thy lover's grace;/\n"
"And, like Limander, am I trusty still.\n"
"Thisbe\n"
"And I like Helen, till the Fates me kill.\n"
"Pyramus\n"
"Not Shafalus to Procrus was so true.\n"
"Thisbe\n"
"As Shafalus to Procrus, I to you.\n"
"Pyramus\n"
"O kiss me through the hole of this vile wall!\n"
"Thisbe\n"
"I kiss the wall's hole, not your lips at all.\n"
"Pyramus\n"
"Wilt thou at Ninny's tomb meet me straightway?\n"
"Thisbe\n"
"'Tide life, 'tide death, I come without delay.\n"
"[Exeunt Pyramus and Thisbe]\n"
"\n"
"Wall\n"
"Thus have I, Wall, my part discharged so;/\n"
"And, being done, thus Wall away doth go.\n"
"Exit\n"
"\n"
"THESEUS\n"
"Now is the mural down between the two neighbours.\n"
"DEMETRIUS\n"
"No remedy, my lord, when walls are so wilful to hear/\n"
"without warning.\n"
"HIPPOLYTA\n"
"This is the silliest stuff that ever I heard.\n"
"THESEUS\n"
"The best in this kind are but shadows; and the worst/\n"
"are no worse, if imagination amend them.\n"
"HIPPOLYTA\n"
"It must be your imagination then, and not theirs.\n"
"THESEUS\n"
"If we imagine no worse of them than they of/\n"
"themselves, they may pass for excellent men. Here/\n"
"come two noble beasts in, a man and a lion.\n"
"[Enter Lion and Moonshine]\n"
"\n"
"Lion\n"
"You, ladies, you, whose gentle hearts do fear/\n"
"The smallest monstrous mouse that creeps on floor,/\n"
"May now perchance both quake and tremble here,/\n"
"When lion rough in wildest rage doth roar./\n"
"Then know that I, one Snug the joiner, am/\n"
"A lion-fell, nor else no lion's dam;/\n"
"For, if I should as lion come in strife/\n"
"Into this place, 'twere pity on my life.\n"
"THESEUS\n"
"A very gentle beast, of a good conscience.\n"
"DEMETRIUS\n"
"The very best at a beast, my lord, that e'er I saw.\n"
"LYSANDER\n"
"This lion is a very fox for his valour.\n"
"THESEUS\n"
"True; and a goose for his discretion.\n"
"DEMETRIUS\n"
"Not so, my lord; for his valour cannot carry his/\n"
"discretion; and the fox carries the goose.\n"
"THESEUS\n"
"His discretion, I am sure, cannot carry his valour;/\n"
"for the goose carries not the fox. It is well:/\n"
"leave it to his discretion, and let us listen to the moon.\n"
"Moonshine\n"
"This lanthorn doth the horned moon present;--\n"
"DEMETRIUS\n"
"He should have worn the horns on his head.\n"
"THESEUS\n"
"He is no crescent, and his horns are/\n"
"invisible within the circumference.\n"
"Moonshine\n"
"This lanthorn doth the horned moon present;/\n"
"Myself the man i' the moon do seem to be.\n"
"THESEUS\n"
"This is the greatest error of all the rest: the man/\n"
"should be put into the lanthorn. How is it else the/\n"
"man i' the moon?\n"
"DEMETRIUS\n"
"He dares not come there for the candle; for, you/\n"
"see, it is already in snuff.\n"
"HIPPOLYTA\n"
"I am aweary of this moon: would he would change!\n"
"THESEUS\n"
"It appears, by his small light of discretion, that/\n"
"he is in the wane; but yet, in courtesy, in all/\n"
"reason, we must stay the time.\n"
"LYSANDER\n"
"Proceed, Moon.\n"
"Moonshine\n"
"All that I have to say, is, to tell you that the/\n"
"lanthorn is the moon; I, the man in the moon; this/\n"
"thorn-bush, my thorn-bush; and this dog, my dog.\n"
"DEMETRIUS\n"
"Why, all these should be in the lanthorn; for all/\n"
"these are in the moon. But, silence! here comes Thisbe.\n"
"[Enter Thisbe]\n"
"\n"
"Thisbe\n"
"This is old Ninny's tomb. Where is my love?\n"
"Lion\n"
"[Roaring] Oh--\n"
"[Thisbe runs off]\n"
"\n"
"DEMETRIUS\n"
"Well roared, Lion.\n"
"THESEUS\n"
"Well run, Thisbe.\n"
"HIPPOLYTA\n"
"Well shone, Moon. Truly, the moon shines with a/\n"
"good grace.\n"
"[The Lion shakes Thisbe's mantle, and exit]\n"
"\n"
"THESEUS\n"
"Well moused, Lion.\n"
"LYSANDER\n"
"And so the lion vanished.\n"
"DEMETRIUS\n"
"And then came Pyramus.\n"
"[Enter Pyramus]\n"
"\n"
"Pyramus\n"
"Sweet Moon, I thank thee for thy sunny beams;/\n"
"I thank thee, Moon, for shining now so bright;/\n"
"For, by thy gracious, golden, glittering gleams,/\n"
"I trust to take of truest Thisby sight./\n"
"But stay, O spite!/\n"
"But mark, poor knight,/\n"
"What dreadful dole is here!/\n"
"Eyes, do you see?/\n"
"How can it be?/\n"
"O dainty duck! O dear!/\n"
"Thy mantle good,/\n"
"What, stain'd with blood!/\n"
"Approach, ye Furies fell!/\n"
"O Fates, come, come,/\n"
"Cut thread and thrum;/\n"
"Quail, crush, conclude, and quell!\n"
"THESEUS\n"
"This passion, and the death of a dear friend, would/\n"
"go near to make a man look sad.\n"
"HIPPOLYTA\n"
"Beshrew my heart, but I pity the man./\n"
"Pyramus\n"
"O wherefore, Nature, didst thou lions frame?/\n"
"Since lion vile hath here deflower'd my dear:/\n"
"Which is--no, no--which was the fairest dame/\n"
"That lived, that loved, that liked, that look'd/\n"
"with cheer./\n"
"Come, tears, confound;/\n"
"Out, sword, and wound/\n"
"The pap of Pyramus;/\n"
"Ay, that left pap,/\n"
"Where heart doth hop:\n"
"[Stabs himself]\n"
"\n"
"Thus die I, thus, thus, thus./\n"
"Now am I dead,/\n"
"Now am I fled;/\n"
"My soul is in the sky:/\n"
"Tongue, lose thy light;/\n"
"Moon take thy flight:/\n"
"[Exit Moonshine]\n"
"\n"
"Now die, die, die, die, die.\n"
"[Dies]\n"
"\n"
"DEMETRIUS\n"
"No die, but an ace, for him; for he is but one.\n"
"LYSANDER\n"
"Less than an ace, man; for he is dead; he is nothing.\n"
"THESEUS\n"
"With the help of a surgeon he might yet recover, and/\n"
"prove an ass.\n"
"HIPPOLYTA\n"
"How chance Moonshine is gone before Thisbe comes/\n"
"back and finds her lover?\n"
"THESEUS\n"
"She will find him by starlight. Here she comes; and/\n"
"her passion ends the play.\n"
"[Re-enter Thisbe]\n"
"\n"
"HIPPOLYTA\n"
"Methinks she should not use a long one for such a/\n"
"Pyramus: I hope she will be brief.\n"
"DEMETRIUS\n"
"A mote will turn the balance, which Pyramus, which/\n"
"Thisbe, is the better; he for a man, God warrant us;/\n"
"she for a woman, God bless us.\n"
"LYSANDER\n"
"She hath spied him already with those sweet eyes.\n"
"DEMETRIUS\n"
"And thus she means, videlicet:--\n"
"Thisbe\n"
"Asleep, my love?/\n"
"What, dead, my dove?/\n"
"O Pyramus, arise!/\n"
"Speak, speak. Quite dumb?/\n"
"Dead, dead? A tomb/\n"
"Must cover thy sweet eyes./\n"
"These lily lips,/\n"
"This cherry nose,/\n"
"These yellow cowslip cheeks,/\n"
"Are gone, are gone:/\n"
"Lovers, make moan:/\n"
"His eyes were green as leeks.\n"
"O Sisters Three,/\n"
"Come, come to me,/\n"
"With hands as pale as milk;/\n"
"Lay them in gore,/\n"
"Since you have shore/\n"
"With shears his thread of silk./\n"
"Tongue, not a word:/\n"
"Come, trusty sword;/\n"
"Come, blade, my breast imbrue:/\n"
"[Stabs herself]\n"
"\n"
"And, farewell, friends;/\n"
"Thus Thisby ends:/\n"
"Adieu, adieu, adieu.\n"
"[Dies]\n"
"\n"
"THESEUS\n"
"Moonshine and Lion are left to bury the dead.\n"
"DEMETRIUS\n"
"Ay, and Wall too.\n"
"BOTTOM\n"
"[Starting up] No assure you; the wall is down that/\n"
"parted their fathers. Will it please you to see the/\n"
"epilogue, or to hear a Bergomask dance between two/\n"
"of our company?\n"
"THESEUS\n"
"No epilogue, I pray you; for your play needs no/\n"
"excuse. Never excuse; for when the players are all/\n"
"dead, there needs none to be blamed. Marry, if he/\n"
"that writ it had played Pyramus and hanged himself/\n"
"in Thisbe's garter, it would have been a fine/\n"
"tragedy: and so it is, truly; and very notably/\n"
"discharged. But come, your Bergomask: let your/\n"
"epilogue alone.";
